In [1]:
%load_ext jupyter_ai

In [2]:
%ai list gemini

gemini
Requires environment variable: GOOGLE_API_KEY (not set)
* gemini:gemini-2.5-pro
* gemini:gemini-2.5-flash
* gemini:gemini-2.0-flash-lite
* gemini:gemini-1.5-pro
* gemini:gemini-1.5-flash

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data/screening_log.csv')

In [5]:
is_record_id_unique = not df['record_id'].duplicated().any()

In [6]:
if is_record_id_unique:
    print("✅ Harika! 'record_id' sütunundaki tüm değerler benzersiz (unique).\n")
else:
    print("❌ Dikkat! 'record_id' sütununda yinelenen değerler bulundu.")
    # Yinelenen 'record_id' değerlerinin sayısını bulalım
    num_duplicates = df['record_id'].duplicated().sum()
    print(f"   Toplam {num_duplicates} adet yinelenen 'record_id' kaydı var.")
    
    # Hangi 'record_id'lerin tekrar ettiğini ve kaçar kez tekrar ettiğini görelim
    duplicated_ids = df['record_id'].value_counts()
    print("   Yinelenen ID'ler ve tekrar sayıları:")
    display(duplicated_ids[duplicated_ids > 1])
    print("-" * 40)

✅ Harika! 'record_id' sütunundaki tüm değerler benzersiz (unique).

In [7]:
df

,record_id,source_db,status,decided_by,decided_at,stage,decision,automation_flag,title,authors,doi_or_id,year,screening_score
0,rec_00001,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Joint Beamforming and Power Control for D2D-As...,"Zhenyu Xue, Yuang Chen, Hancheng Lu, Baolin Ch...",10.1109/globecom52923.2024.10901750,-,2.5
1,rec_00002,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Integrated Sensing and Communications With Mix...,"Yun Xiao, Enhao Wa, Yunfei Chen, Li Chen, Aiss...",10.1109/lwc.2024.3521186,-,2.7
2,rec_00003,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,"Waveform Design for Integrated Radar, Communic...","Qi Cheng, Yanjie Ji, Xuezhou Yang, Li Zhou, Ju...",10.1109/icwoc65853.2025.11151123,-,2.7
3,rec_00004,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Precoding for Multi-Cell ISAC: From Coordinate...,"Nithin Babu, Christos Masouros, Constantinos B...",10.1109/twc.2024.3417713,2024,2.5
4,rec_00005,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,SDOA-Net: An Efficient Deep-Learning-Based DOA...,"Peng Chen, Zhimin Chen, Liang Liu, Yun Chen, X...",10.1109/tim.2024.3391338,-,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,rec_00753,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Algorithm Design and Prototype Validation for ...,"Cheng Luo, Luping Xiang, Jie Hu, Kun Yang",10.1109/twc.2025.3599545,2025,2.7
753,rec_00754,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Reconfigurable Intelligent Surface assisted In...,"Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu, ...",10.1109/icasspw62465.2024.10626004,-,2.7
754,rec_00755,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Performance of Massive MIMO aided by Reflectiv...,"André Flaiban, André Flaiban, Taufik Abrão",10.1007/s10922-024-09846-4,-,2.5
755,R002,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474334Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN
756,R004,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474612Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# --- Kural 2: 'title' sütunu benzersiz olmalı ---
print("\n--- Kural 2: 'title' Sütunu Kontrolü ---")

# 'title' sütununda yinelenen değer var mı?
is_title_unique = not df['title'].duplicated().any()

if is_title_unique:
    print("✅ Harika! 'title' sütunundaki tüm değerler benzersiz (unique).\n")
else:
    print("❌ Dikkat! 'title' sütununda yinelenen değerler bulundu.")
    # Yinelenen 'title' değerlerinin sayısını bulalım
    num_duplicates = df['title'].duplicated().sum()
    print(f"   Toplam {num_duplicates} adet yinelenen 'title' kaydı var.")

    # Hangi 'title'ların tekrar ettiğini ve kaçar kez tekrar ettiğini görelim
    duplicated_titles = df['title'].value_counts()
    print("   Yinelenen Başlıklar ve tekrar sayıları:")
    display(duplicated_titles[duplicated_titles > 1])
    print("-" * 40)

--- Kural 2: 'title' Sütunu Kontrolü ---
❌ Dikkat! 'title' sütununda yinelenen değerler bulundu.
   Toplam 23 adet yinelenen 'title' kaydı var.
   Yinelenen Başlıklar ve tekrar sayıları:

title
Optical Integrated Sensing and Communication System Based on Combination of OIRS and PD Array for Mobile Scenarios         3
Hybrid NOMA Assisted Integrated Sensing and Communication via RIS                                                          2
Joint Waveform and Phase Shift Design for RIS-Assisted Integrated Sensing and Communication Based on Mutual Information    2
A RIS-Based Vehicle DOA Estimation Method With Integrated Sensing and Communication System                                 2
Optical Integrated Sensing and Communication: Architectures, Potentials and Challenges                                     2
Joint Resource Allocation and Reflecting Precoding Design for RIS-Assisted ISAC Systems                                    2
Recent advances in integrated sensing and communication: a synergistic perspective                                         2
Photonics-assisted Millimeter-Wave Multiband Integrated Sensing and Communication System Using Coherent Receiving          2
Beamforming in Hybrid RIS assisted Integrated Sensing and Communication Systems                                            2
Enhancing Battlefield Awareness: An Aerial RIS-assisted ISAC System with Deep Reinforcement Learning                       2
Joint Localization and Information Transfer for RIS Aided Full-Duplex Systems                                              2
Fully Autonomous Reconfigurable Metasurfaces with Integrated Sensing and Communication                                     2
Rate-Splitting Multiple Access for Transmissive Reconfigurable Intelligent Surface Transceiver Empowered ISAC Systems      2
Nested Tensor-Based Framework for ISAC Assisted by Reconfigurable Intelligent Surface                                      2
Joint Beamforming for RIS-Assisted Integrated Communication, Sensing and Power Transfer Systems                            2
Sum Secrecy Rate Optimization in RIS-Assisted ISAC Systems: A Manifold-Based Framework                                     2
Joint Beamforming for RIS-Assisted Integrated Sensing and Communication Systems                                            2
Transmit Beamforming Design for ISAC With Stacked Intelligent Metasurfaces                                                 2
Circular RIS-Enabled Channel Estimation and Localization for Multi-User ISAC Systems                                       2
Optical Integrated Sensing and Communication with Light-Emitting Diode                                                     2
Simultaneous Beam Training and Target Sensing in ISAC Systems With RIS                                                     2
Name: count, dtype: int64

----------------------------------------

In [9]:
duplicated_df = df[df['record_id'].duplicated(keep=False)]
display(duplicated_df[['record_id']])

Empty DataFrame
Columns: [record_id]
Index: []

In [10]:
duplicated_titles_df = df[df['title'].duplicated(keep=False)]
display(duplicated_titles_df[['title', 'record_id']])

                                                 title  record_id
20   Joint Waveform and Phase Shift Design for RIS-...  rec_00021
36   A RIS-Based Vehicle DOA Estimation Method With...  rec_00037
53   Joint Resource Allocation and Reflecting Preco...  rec_00054
77   Recent advances in integrated sensing and comm...  rec_00078
85   Photonics-assisted Millimeter-Wave Multiband I...  rec_00086
97   Nested Tensor-Based Framework for ISAC Assiste...  rec_00098
98   Joint Beamforming for RIS-Assisted Integrated ...  rec_00099
99   Hybrid NOMA Assisted Integrated Sensing and Co...  rec_00100
100  Joint Beamforming for RIS-Assisted Integrated ...  rec_00101
102  Circular RIS-Enabled Channel Estimation and Lo...  rec_00103
103  Simultaneous Beam Training and Target Sensing ...  rec_00104
105  Transmit Beamforming Design for ISAC With Stac...  rec_00106
106  Sum Secrecy Rate Optimization in RIS-Assisted ...  rec_00107
107  Rate-Splitting Multiple Access for Transmissiv...  rec_00108
109  Fully Autonomous Reconfigurable Metasurfaces w...  rec_00110
110  Joint Localization and Information Transfer fo...  rec_00111
111  Enhancing Battlefield Awareness: An Aerial RIS...  rec_00112
112  Sum Secrecy Rate Optimization in RIS-Assisted ...  rec_00113
113  Beamforming in Hybrid RIS assisted Integrated ...  rec_00114
161  Optical Integrated Sensing and Communication S...  rec_00162
170  Optical Integrated Sensing and Communication w...  rec_00171
222  Optical Integrated Sensing and Communication S...  rec_00223
240  Optical Integrated Sensing and Communication: ...  rec_00241
281  Hybrid NOMA Assisted Integrated Sensing and Co...  rec_00282
286  Beamforming in Hybrid RIS assisted Integrated ...  rec_00287
287  Joint Waveform and Phase Shift Design for RIS-...  rec_00288
291  Simultaneous Beam Training and Target Sensing ...  rec_00292
306  Joint Beamforming for RIS-Assisted Integrated ...  rec_00307
311  Fully Autonomous Reconfigurable Metasurfaces w...  rec_00312
313  Transmit Beamforming Design for ISAC With Stac...  rec_00314
323  Recent advances in integrated sensing and comm...  rec_00324
363  Nested Tensor-Based Framework for ISAC Assiste...  rec_00364
372  Optical Integrated Sensing and Communication w...  rec_00373
376  Enhancing Battlefield Awareness: An Aerial RIS...  rec_00377
425  Joint Localization and Information Transfer fo...  rec_00426
452  Optical Integrated Sensing and Communication: ...  rec_00453
453  A RIS-Based Vehicle DOA Estimation Method With...  rec_00454
462  Circular RIS-Enabled Channel Estimation and Lo...  rec_00463
484  Rate-Splitting Multiple Access for Transmissiv...  rec_00485
564  Joint Resource Allocation and Reflecting Preco...  rec_00565
572  Photonics-assisted Millimeter-Wave Multiband I...  rec_00573
590  Joint Beamforming for RIS-Assisted Integrated ...  rec_00591
615  Optical Integrated Sensing and Communication S...  rec_00616
755                                                NaN       R002
756                                                NaN       R004

In [11]:
print(df.columns.tolist())

['record_id', 'source_db', 'status', 'decided_by', 'decided_at', 'stage', 'decision', 'automation_flag', 'title', 'authors', 'doi_or_id', 'year', 'screening_score']

In [12]:
duplicated_titles_df = df[df['title'].duplicated(keep=False)]
display(duplicated_titles_df[['title', 'authors']])

,title,authors
20,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang
36,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang..."
53,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng"
77,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang"
85,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Zh..."
97,Nested Tensor-Based Framework for ISAC Assiste...,"Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, X..."
98,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo..."
99,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang..."
100,Joint Beamforming for RIS-Assisted Integrated ...,"Yongqing Xu, Yong Li, J Andrew Zhang, Marco Di..."
102,Circular RIS-Enabled Channel Estimation and Lo...,"Yuxing Lin, Shi Jin, Xinping Yi, Michail Matth..."
103,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, Octavia A Dobre, Ge..."
105,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoch..."
106,Sum Secrecy Rate Optimization in RIS-Assisted ...,"Mohamed Elsayed, Mahmoud H Ismail, Ahmed Samir..."
107,Rate-Splitting Multiple Access for Transmissiv...,"Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan ..."
109,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, Gabriele..."
110,Joint Localization and Information Transfer fo...,"Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco D..."
111,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J..."
112,Sum Secrecy Rate Optimization in RIS-Assisted ...,-
113,Beamforming in Hybrid RIS assisted Integrated ...,"R S Prasobh Sankar, Sundeep Prabhakar Chepuri"
161,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch..."
170,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y..."
222,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch..."
240,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han"
281,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang..."
286,Beamforming in Hybrid RIS assisted Integrated ...,"R. Sankar, S. Chepuri"
287,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang
291,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, O. Dobre, Geoffrey ..."
306,Joint Beamforming for RIS-Assisted Integrated ...,"Graduate Student Member Ieee Yongqing Xu, Memb..."
311,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, G. Grado..."
313,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zhang, Tianqi Mao, Rui Na, Zhao..."
323,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang"
363,Nested Tensor-Based Framework for ISAC Assiste...,"Yuan Cheng, Jianhe Du, Jianbo Liu, Libiao Jin,..."
372,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y..."
376,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J..."
425,Joint Localization and Information Transfer fo...,"Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo"
452,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han"
453,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang..."
462,Circular RIS-Enabled Channel Estimation and Lo...,"Yuxing Lin, Shi Jin, M. Matthaiou, Xinping Yi"
484,Rate-Splitting Multiple Access for Transmissiv...,"Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yua..."
564,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng"
572,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhong..."
590,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo..."
615,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bin Zhu"
755,NaN,NaN
756,NaN,NaN

In [13]:
grouped = duplicated_titles_df.groupby('title')['authors'].apply(list).reset_index()
display(grouped)

,title,authors
0,A RIS-Based Vehicle DOA Estimation Method With...,"[Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhan..."
1,Beamforming in Hybrid RIS assisted Integrated ...,"[R S Prasobh Sankar, Sundeep Prabhakar Chepuri..."
2,Circular RIS-Enabled Channel Estimation and Lo...,"[Yuxing Lin, Shi Jin, Xinping Yi, Michail Matt..."
3,Enhancing Battlefield Awareness: An Aerial RIS...,"[Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, ..."
4,Fully Autonomous Reconfigurable Metasurfaces w...,"[Hamidreza Taghvaee, Maryam Khodadadi, Gabriel..."
5,Hybrid NOMA Assisted Integrated Sensing and Co...,"[Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yan..."
6,Joint Beamforming for RIS-Assisted Integrated ...,"[Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Y..."
7,Joint Beamforming for RIS-Assisted Integrated ...,"[Yongqing Xu, Yong Li, J Andrew Zhang, Marco D..."
8,Joint Localization and Information Transfer fo...,"[Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco ..."
9,Joint Resource Allocation and Reflecting Preco...,"[Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sh..."
10,Joint Waveform and Phase Shift Design for RIS-...,"[Hongliang Zhang, Hongliang Zhang]"
11,Nested Tensor-Based Framework for ISAC Assiste...,"[Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, ..."
12,Optical Integrated Sensing and Communication S...,"[Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingc..."
13,Optical Integrated Sensing and Communication w...,"[Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, ..."
14,Optical Integrated Sensing and Communication: ...,"[Yunfeng Wen, Fang Yang, Jian Song, Zhu Han, Y..."
15,Photonics-assisted Millimeter-Wave Multiband I...,"[Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Z..."
16,Rate-Splitting Multiple Access for Transmissiv...,"[Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan..."
17,Recent advances in integrated sensing and comm...,"[Yufeng Zhang, Minglun Zhang, Yufeng Zhang, Mi..."
18,Simultaneous Beam Training and Target Sensing ...,"[Kangjian Chen, Chenhao Qi, Octavia A Dobre, G..."
19,Sum Secrecy Rate Optimization in RIS-Assisted ...,"[Mohamed Elsayed, Mahmoud H Ismail, Ahmed Sami..."
20,Transmit Beamforming Design for ISAC With Stac...,"[Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoc..."

In [14]:
duplications = duplicated_titles_df.groupby('title')['authors'].apply(list).reset_index()
duplications = duplications.set_index('title').transpose()
display(duplications)

title,A RIS-Based Vehicle DOA Estimation Method With Integrated Sensing and Communication System,Beamforming in Hybrid RIS assisted Integrated Sensing and Communication Systems,Circular RIS-Enabled Channel Estimation and Localization for Multi-User ISAC Systems,Enhancing Battlefield Awareness: An Aerial RIS-assisted ISAC System with Deep Reinforcement Learning,Fully Autonomous Reconfigurable Metasurfaces with Integrated Sensing and Communication,Hybrid NOMA Assisted Integrated Sensing and Communication via RIS,"Joint Beamforming for RIS-Assisted Integrated Communication, Sensing and Power Transfer Systems",Joint Beamforming for RIS-Assisted Integrated Sensing and Communication Systems,Joint Localization and Information Transfer for RIS Aided Full-Duplex Systems,Joint Resource Allocation and Reflecting Precoding Design for RIS-Assisted ISAC Systems,...,Nested Tensor-Based Framework for ISAC Assisted by Reconfigurable Intelligent Surface,Optical Integrated Sensing and Communication System Based on Combination of OIRS and PD Array for Mobile Scenarios,Optical Integrated Sensing and Communication with Light-Emitting Diode,"Optical Integrated Sensing and Communication: Architectures, Potentials and Challenges",Photonics-assisted Millimeter-Wave Multiband Integrated Sensing and Communication System Using Coherent Receiving,Rate-Splitting Multiple Access for Transmissive Reconfigurable Intelligent Surface Transceiver Empowered ISAC Systems,Recent advances in integrated sensing and communication: a synergistic perspective,Simultaneous Beam Training and Target Sensing in ISAC Systems With RIS,Sum Secrecy Rate Optimization in RIS-Assisted ISAC Systems: A Manifold-Based Framework,Transmit Beamforming Design for ISAC With Stacked Intelligent Metasurfaces
authors,"[Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhan...","[R S Prasobh Sankar, Sundeep Prabhakar Chepuri...","[Yuxing Lin, Shi Jin, Xinping Yi, Michail Matt...","[Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, ...","[Hamidreza Taghvaee, Maryam Khodadadi, Gabriel...","[Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yan...","[Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Y...","[Yongqing Xu, Yong Li, J Andrew Zhang, Marco D...","[Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco ...","[Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sh...",...,"[Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, ...","[Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingc...","[Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, ...","[Yunfeng Wen, Fang Yang, Jian Song, Zhu Han, Y...","[Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Z...","[Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan...","[Yufeng Zhang, Minglun Zhang, Yufeng Zhang, Mi...","[Kangjian Chen, Chenhao Qi, Octavia A Dobre, G...","[Mohamed Elsayed, Mahmoud H Ismail, Ahmed Sami...","[Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoc..."

In [15]:
# Duplicate başlıkları bul ve tekrar sayılarını, yazarlarını ve record_id'leri grupla:
grouped = duplicated_titles_df.groupby('title').agg({
    'authors': list,
    'record_id': list,
}).reset_index()
grouped['repeat_count'] = grouped['record_id'].apply(len)
display(grouped)

,title,authors,record_id,repeat_count
0,A RIS-Based Vehicle DOA Estimation Method With...,"[Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhan...","[rec_00037, rec_00454]",2
1,Beamforming in Hybrid RIS assisted Integrated ...,"[R S Prasobh Sankar, Sundeep Prabhakar Chepuri...","[rec_00114, rec_00287]",2
2,Circular RIS-Enabled Channel Estimation and Lo...,"[Yuxing Lin, Shi Jin, Xinping Yi, Michail Matt...","[rec_00103, rec_00463]",2
3,Enhancing Battlefield Awareness: An Aerial RIS...,"[Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, ...","[rec_00112, rec_00377]",2
4,Fully Autonomous Reconfigurable Metasurfaces w...,"[Hamidreza Taghvaee, Maryam Khodadadi, Gabriel...","[rec_00110, rec_00312]",2
5,Hybrid NOMA Assisted Integrated Sensing and Co...,"[Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yan...","[rec_00100, rec_00282]",2
6,Joint Beamforming for RIS-Assisted Integrated ...,"[Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Y...","[rec_00099, rec_00591]",2
7,Joint Beamforming for RIS-Assisted Integrated ...,"[Yongqing Xu, Yong Li, J Andrew Zhang, Marco D...","[rec_00101, rec_00307]",2
8,Joint Localization and Information Transfer fo...,"[Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco ...","[rec_00111, rec_00426]",2
9,Joint Resource Allocation and Reflecting Preco...,"[Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sh...","[rec_00054, rec_00565]",2
10,Joint Waveform and Phase Shift Design for RIS-...,"[Hongliang Zhang, Hongliang Zhang]","[rec_00021, rec_00288]",2
11,Nested Tensor-Based Framework for ISAC Assiste...,"[Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, ...","[rec_00098, rec_00364]",2
12,Optical Integrated Sensing and Communication S...,"[Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingc...","[rec_00162, rec_00223, rec_00616]",3
13,Optical Integrated Sensing and Communication w...,"[Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, ...","[rec_00171, rec_00373]",2
14,Optical Integrated Sensing and Communication: ...,"[Yunfeng Wen, Fang Yang, Jian Song, Zhu Han, Y...","[rec_00241, rec_00453]",2
15,Photonics-assisted Millimeter-Wave Multiband I...,"[Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Z...","[rec_00086, rec_00573]",2
16,Rate-Splitting Multiple Access for Transmissiv...,"[Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan...","[rec_00108, rec_00485]",2
17,Recent advances in integrated sensing and comm...,"[Yufeng Zhang, Minglun Zhang, Yufeng Zhang, Mi...","[rec_00078, rec_00324]",2
18,Simultaneous Beam Training and Target Sensing ...,"[Kangjian Chen, Chenhao Qi, Octavia A Dobre, G...","[rec_00104, rec_00292]",2
19,Sum Secrecy Rate Optimization in RIS-Assisted ...,"[Mohamed Elsayed, Mahmoud H Ismail, Ahmed Sami...","[rec_00107, rec_00113]",2
20,Transmit Beamforming Design for ISAC With Stac...,"[Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoc...","[rec_00106, rec_00314]",2

In [16]:
duplicated_record_ids_df = df[df['record_id'].duplicated(keep=False)]
grouped = duplicated_record_ids_df.groupby('record_id').agg({
    'title': list
}).reset_index()
grouped['distinct_title_count'] = grouped['title'].apply(lambda x: len(set(x)))
display(grouped[grouped['distinct_title_count'] > 1])

Empty DataFrame
Columns: [record_id, title, distinct_title_count]
Index: []

In [18]:
import pandas as pd
import os

# Dosya yolunu düzelt
file_path = 'data/included_studies.csv'
if not os.path.exists(file_path):
    print(f"❌ Dosya bulunamadı: {file_path}")
    print(f"Mevcut dizin: {os.getcwd()}")
    print(f"Dizindeki dosyalar: {os.listdir('.')}")
else:
    # Dosyayı oku
    df_included = pd.read_csv(file_path)
    
    # DataFrame bilgilerini göster
    print(f"Toplam kayıt sayısı: {len(df_included)}")
    print(f"\nSütunlar: {df_included.columns.tolist()}")
    print(f"\nİlk 5 satır:")
    print(df_included.head())
    
    # record_id duplicate kontrolü
    print("\n" + "="*80)
    print("RECORD_ID DUPLICATE KONTROLÜ")
    print("="*80)
    record_id_dups = df_included[df_included['record_id'].duplicated(keep=False)]
    if len(record_id_dups) > 0:
        print(f"❌ {len(record_id_dups)} kayıtta record_id tekrarı bulundu!")
        print(f"Tekrar eden benzersiz record_id sayısı: {record_id_dups['record_id'].nunique()}")
        print("\nTekrar eden record_id'ler:")
        print(record_id_dups[['record_id', 'title']].sort_values('record_id'))
    else:
        print("✅ record_id sütununda duplicate YOK")
    
    # title duplicate kontrolü
    print("\n" + "="*80)
    print("TITLE DUPLICATE KONTROLÜ")
    print("="*80)
    title_dups = df_included[df_included['title'].duplicated(keep=False)]
    if len(title_dups) > 0:
        print(f"❌ {len(title_dups)} kayıtta title tekrarı bulundu!")
        print(f"Tekrar eden benzersiz title sayısı: {title_dups['title'].nunique()}")
        print("\nTekrar eden title'lar ve record_id'leri:")
        print(title_dups[['record_id', 'title']].sort_values('title'))
    else:
        print("✅ title sütununda duplicate YOK")
    
    # Özet
    print("\n" + "="*80)
    print("ÖZET")
    print("="*80)
    print(f"Toplam kayıt: {len(df_included)}")
    print(f"record_id duplicate: {len(record_id_dups)} kayıt")
    print(f"title duplicate: {len(title_dups)} kayıt")

Toplam kayıt sayısı: 660

Sütunlar: ['record_id', 'title', 'authors', 'year', 'venue', 'doi', 'url', 'citation', 'pub_type', 'peer_reviewed']

İlk 5 satır:
   record_id                                              title  \
0  rec_00702  1- bit Reconfigurable Intelligent Surface for ...
1  rec_00158  1000-Channel Integrated Optical Phased Array w...
2  rec_00585  2-Bit RIS Prototyping Enhancing Rapid-Response...
3  rec_00040  6G INTEGRATED SENSING AND COMMUNICATION -SENSI...
4  rec_00033  A Beam-scannable photonic THz-ISAC system base...

                                             authors  year  \
0              Deepak, Akhila Gouda, Saptarshi Ghosh  2025
1                            Yong Liu, Xiansong Meng     -
2  Yufei Zhao, Yuan Feng, Afkar Mohamed Ismail, Z...  2024
3  Zhi Zhou, Xianjin Li, Jia He, Xiaoyan Bi, Yan ...     -
4  Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...     -

                                               venue  \
0  2025 Third International Conference on Microwa...
1                                                NaN
2    IEEE Open Journal of the Communications Society
3                                                NaN
4                                                NaN

                                   doi  \
0       10.1109/MAC64480.2025.11140492
1                     arXiv:2508.19977
2          10.1109/OJCOMS.2024.3439558
3    10.1109/icassp49357.2023.10096544
4  10.1109/acp/poem59049.2023.10368958

                                              url  citation  pub_type  \
0  https://doi.org/10.1109/MAC64480.2025.11140492       NaN       NaN
1                                               -       NaN       NaN
2     https://doi.org/10.1109/OJCOMS.2024.3439558       NaN       NaN
3                                               -       NaN       NaN
4                                               -       NaN       NaN

   peer_reviewed
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN

================================================================================
RECORD_ID DUPLICATE KONTROLÜ
================================================================================
❌ 94 kayıtta record_id tekrarı bulundu!
Tekrar eden benzersiz record_id sayısı: 40

Tekrar eden record_id'ler:
     record_id                                              title
337  rec_00021  Joint Waveform and Phase Shift Design for RIS-...
336  rec_00021  Joint Waveform and Phase Shift Design for RIS-...
4    rec_00033  A Beam-scannable photonic THz-ISAC system base...
5    rec_00033  A Beam-Scannable Photonic THz-ISAC System Base...
27   rec_00037  A RIS-Based Vehicle DOA Estimation Method With...
..         ...                                                ...
202  rec_00744   Holographic Integrated Sensing and Communication
479  rec_00754  Reconfigurable Intelligent Surface Assisted In...
478  rec_00754  Reconfigurable Intelligent Surface assisted In...
389        NaN                                     No title found
390        NaN                                     No title found

[94 rows x 2 columns]

================================================================================
TITLE DUPLICATE KONTROLÜ
================================================================================
❌ 41 kayıtta title tekrarı bulundu!
Tekrar eden benzersiz title sayısı: 20

Tekrar eden title'lar ve record_id'leri:
     record_id                                              title
27   rec_00037  A RIS-Based Vehicle DOA Estimation Method With...
28   rec_00037  A RIS-Based Vehicle DOA Estimation Method With...
83   rec_00114  Beamforming in Hybrid RIS assisted Integrated ...
84   rec_00114  Beamforming in Hybrid RIS assisted Integrated ...
164  rec_00112  Enhancing Battlefield Awareness: An Aerial RIS...
165  rec_00112  Enhancing Battlefield Awareness: An Aerial RIS...
187  rec_00110  Fully Autonomous Reconfigurable Metasurfaces w...
188  rec_00110  Fully Autonomous Reconfigurable Metasurfaces w...
208  rec_00100  Hybrid NOMA Assisted Integrated Sensing and Co...
209  rec_00100  Hybrid NOMA Assisted Integrated Sensing and Co...
298  rec_00099  Joint Beamforming for RIS-Assisted Integrated ...
297  rec_00099  Joint Beamforming for RIS-Assisted Integrated ...
299  rec_00263  Joint Beamforming for RIS-Assisted Integrated ...
300  rec_00263  Joint Beamforming for RIS-Assisted Integrated ...
312  rec_00111  Joint Localization and Information Transfer fo...
313  rec_00111  Joint Localization and Information Transfer fo...
321  rec_00054  Joint Resource Allocation and Reflecting Preco...
322  rec_00054  Joint Resource Allocation and Reflecting Preco...
336  rec_00021  Joint Waveform and Phase Shift Design for RIS-...
337  rec_00021  Joint Waveform and Phase Shift Design for RIS-...
386  rec_00098  Nested Tensor-Based Framework for ISAC Assiste...
385  rec_00098  Nested Tensor-Based Framework for ISAC Assiste...
389        NaN                                     No title found
390        NaN                                     No title found
402  rec_00408  Optical Integrated Sensing and Communication S...
403  rec_00408  Optical Integrated Sensing and Communication S...
404  rec_00408  Optical Integrated Sensing and Communication S...
406  rec_00408  Optical Integrated Sensing and Communication w...
407  rec_00408  Optical Integrated Sensing and Communication w...
408  rec_00408  Optical Integrated Sensing and Communication: ...
409  rec_00408  Optical Integrated Sensing and Communication: ...
446  rec_00086  Photonics-assisted Millimeter-Wave Multiband I...
445  rec_00086  Photonics-assisted Millimeter-Wave Multiband I...
465  rec_00108  Rate-Splitting Multiple Access for Transmissiv...
466  rec_00108  Rate-Splitting Multiple Access for Transmissiv...
470  rec_00078  Recent advances in integrated sensing and comm...
471  rec_00078  Recent advances in integrated sensing and comm...
579  rec_00104  Simultaneous Beam Training and Target Sensing ...
580  rec_00104  Simultaneous Beam Training and Target Sensing ...
637  rec_00106  Transmit Beamforming Design for ISAC With Stac...
638  rec_00106  Transmit Beamforming Design for ISAC With Stac...

================================================================================
ÖZET
================================================================================
Toplam kayıt: 660
record_id duplicate: 94 kayıt
title duplicate: 41 kayıt

In [19]:
import pandas as pd
included = pd.read_csv('data/included_studies.csv')

duplicate_records = included[included.duplicated(subset=['record_id', 'title'], keep=False)]
groups = duplicate_records.groupby(['record_id', 'title']).size().reset_index(name='dupe_count')
display(groups)

display(duplicate_records)

    record_id                                              title  dupe_count
0   rec_00021  Joint Waveform and Phase Shift Design for RIS-...           2
1   rec_00037  A RIS-Based Vehicle DOA Estimation Method With...           2
2   rec_00054  Joint Resource Allocation and Reflecting Preco...           2
3   rec_00078  Recent advances in integrated sensing and comm...           2
4   rec_00086  Photonics-assisted Millimeter-Wave Multiband I...           2
5   rec_00098  Nested Tensor-Based Framework for ISAC Assiste...           2
6   rec_00099  Joint Beamforming for RIS-Assisted Integrated ...           2
7   rec_00100  Hybrid NOMA Assisted Integrated Sensing and Co...           2
8   rec_00104  Simultaneous Beam Training and Target Sensing ...           2
9   rec_00106  Transmit Beamforming Design for ISAC With Stac...           2
10  rec_00108  Rate-Splitting Multiple Access for Transmissiv...           2
11  rec_00110  Fully Autonomous Reconfigurable Metasurfaces w...           2
12  rec_00111  Joint Localization and Information Transfer fo...           2
13  rec_00112  Enhancing Battlefield Awareness: An Aerial RIS...           2
14  rec_00114  Beamforming in Hybrid RIS assisted Integrated ...           2
15  rec_00263  Joint Beamforming for RIS-Assisted Integrated ...           2
16  rec_00408  Optical Integrated Sensing and Communication S...           3
17  rec_00408  Optical Integrated Sensing and Communication w...           2
18  rec_00408  Optical Integrated Sensing and Communication: ...           2

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
27,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2024,NaN,10.1109/tits.2023.3330172,-,NaN,NaN,NaN
28,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2022,IEEE transactions on intelligent transportatio...,10.1109/tits.2023.3330172,https://doi.org/10.1109/TITS.2023.3330172,NaN,NaN,NaN
83,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R. Sankar, S. Chepuri",2022,European Signal Processing Conference,10.23919/eusipco55093.2022.9909562,https://doi.org/10.48550/arXiv.2203.05902,NaN,NaN,NaN
84,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R S Prasobh Sankar, Sundeep Prabhakar Chepuri",-,NaN,10.23919/eusipco55093.2022.9909562,-,NaN,NaN,NaN
164,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",2024,IEEE Military Communications Conference,10.1109/milcom61039.2024.10774028,https://doi.org/10.1109/MILCOM61039.2024.10774028,NaN,NaN,NaN
165,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",-,NaN,10.1109/milcom61039.2024.10774028,-,NaN,NaN,NaN
187,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, Gabriele...",-,NaN,10.23919/eucap60739.2024.10501539,-,NaN,NaN,NaN
188,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, G. Grado...",2024,European Conference on Antennas and Propagation,10.23919/eucap60739.2024.10501539,https://doi.org/10.23919/EuCAP60739.2024.10501539,NaN,NaN,NaN
208,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,NaN,10.1109/tvt.2023.3343379,-,NaN,NaN,NaN
209,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3343379,https://doi.org/10.1109/TVT.2023.3343379,NaN,NaN,NaN
297,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",2024,IEEE Wireless Communications Letters,10.1109/lwc.2023.3327360,https://doi.org/10.1109/LWC.2023.3327360,NaN,NaN,NaN
298,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",-,NaN,10.1109/lwc.2023.3327360,-,NaN,NaN,NaN
299,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Yongqing Xu, Yong Li, J Andrew Zhang, Marco Di...",2023,NaN,10.1109/TVT.2022.3197448,-,NaN,NaN,NaN
300,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Graduate Student Member Ieee Yongqing Xu, Memb...",2023,IEEE Transactions on Communications,10.1109/TVT.2022.3197448,https://doi.org/10.1109/TCOMM.2023.3344143,NaN,NaN,NaN
312,rec_00111,Joint Localization and Information Transfer fo...,"Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo",2022,Global Communications Conference,10.1109/globecom48099.2022.10001508,https://doi.org/10.1109/GLOBECOM48099.2022.100...,NaN,NaN,NaN
313,rec_00111,Joint Localization and Information Transfer fo...,"Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco D...",-,NaN,10.1109/globecom48099.2022.10001508,-,NaN,NaN,NaN
321,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",2024,IEEE Wireless Communications Letters,10.1109/lwc.2024.3365809,https://doi.org/10.1109/LWC.2024.3365809,NaN,NaN,NaN
322,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",-,NaN,10.1109/lwc.2024.3365809,-,NaN,NaN,NaN
336,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,2022,IEEE Communications Letters,10.1109/lcomm.2022.3195062,https://doi.org/10.1109/LCOMM.2022.3195062,NaN,NaN,NaN
337,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,-,NaN,10.1109/lcomm.2022.3195062,-,NaN,NaN,NaN
385,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, X...",-,NaN,10.1109/tvt.2023.3324448,-,NaN,NaN,NaN
386,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yuan Cheng, Jianhe Du, Jianbo Liu, Libiao Jin,...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3324448,https://doi.org/10.1109/TVT.2023.3324448,NaN,NaN,NaN
389,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
390,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
402,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
403,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
404,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bin Zhu",2024,IEEE Transactions on Wireless Communications,10.48550/arXiv.2305.04395,https://doi.org/10.1109/TWC.2024.3484569,NaN,NaN,NaN
406,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,2024 IEEE International Conference on Communic...,10.48550/arXiv.2305.04395,https://doi.org/10.1109/ICCWorkshops59551.2024...,NaN,NaN,NaN
407,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
408,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2023,IEEE Internet of Things Magazine,10.48550/arXiv.2305.04395,https://doi.org/10.1109/IOTM.001.2300196,NaN,NaN,NaN
409,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
445,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhong...",2023,IEEE Journal of Selected Topics in Quantum Ele...,10.1109/jstqe.2023.3276903,https://doi.org/10.1109/JSTQE.2023.3276903,NaN,NaN,NaN
446,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Zh...",-,NaN,10.1109/jstqe.2023.3276903,-,NaN,NaN,NaN
465,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yua...",2024,IEEE Internet of Things Journal,10.1109/jiot.2024.3397736,https://doi.org/10.1109/JIOT.2024.3397736,NaN,NaN,NaN
466,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan ...",-,NaN,10.1109/jiot.2024.3397736,-,NaN,NaN,NaN
470,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",2024,2024 4th International Conference on Neural Ne...,10.1109/nnice61279.2024.10498998,https://doi.org/10.1109/NNICE61279.2024.10498998,NaN,NaN,NaN
471,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",-,NaN,10.1109/nnice61279.2024.10498998,-,NaN,NaN,NaN
579,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, Octavia A Dobre, Ge...",2024,NaN,10.1109/twc.2023.3302319,-,NaN,NaN,NaN
580,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, O. Dobre, Geoffrey ...",2023,IEEE Transactions on Wireless Communications,10.1109/twc.2023.3302319,https://doi.org/10.1109/TWC.2023.3302319,NaN,NaN,NaN
637,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoch...",2025,NaN,10.1109/tvt.2024.3517709,-,NaN,NaN,NaN
638,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zhang, Tianqi Mao, Rui Na, Zhao...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2024.3517709,https://doi.org/10.1109/TVT.2024.3517709,NaN,NaN,NaN

In [20]:
duplicate_titles = included[included.duplicated(subset=['title'], keep=False)]
title_groups = duplicate_titles.groupby('title').size().reset_index(name='dupe_count')
display(title_groups)
display(duplicate_titles)

                                                title  dupe_count
0   A RIS-Based Vehicle DOA Estimation Method With...           2
1   Beamforming in Hybrid RIS assisted Integrated ...           2
2   Enhancing Battlefield Awareness: An Aerial RIS...           2
3   Fully Autonomous Reconfigurable Metasurfaces w...           2
4   Hybrid NOMA Assisted Integrated Sensing and Co...           2
5   Joint Beamforming for RIS-Assisted Integrated ...           2
6   Joint Beamforming for RIS-Assisted Integrated ...           2
7   Joint Localization and Information Transfer fo...           2
8   Joint Resource Allocation and Reflecting Preco...           2
9   Joint Waveform and Phase Shift Design for RIS-...           2
10  Nested Tensor-Based Framework for ISAC Assiste...           2
11                                     No title found           2
12  Optical Integrated Sensing and Communication S...           3
13  Optical Integrated Sensing and Communication w...           2
14  Optical Integrated Sensing and Communication: ...           2
15  Photonics-assisted Millimeter-Wave Multiband I...           2
16  Rate-Splitting Multiple Access for Transmissiv...           2
17  Recent advances in integrated sensing and comm...           2
18  Simultaneous Beam Training and Target Sensing ...           2
19  Transmit Beamforming Design for ISAC With Stac...           2

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
27,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2024,NaN,10.1109/tits.2023.3330172,-,NaN,NaN,NaN
28,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2022,IEEE transactions on intelligent transportatio...,10.1109/tits.2023.3330172,https://doi.org/10.1109/TITS.2023.3330172,NaN,NaN,NaN
83,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R. Sankar, S. Chepuri",2022,European Signal Processing Conference,10.23919/eusipco55093.2022.9909562,https://doi.org/10.48550/arXiv.2203.05902,NaN,NaN,NaN
84,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R S Prasobh Sankar, Sundeep Prabhakar Chepuri",-,NaN,10.23919/eusipco55093.2022.9909562,-,NaN,NaN,NaN
164,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",2024,IEEE Military Communications Conference,10.1109/milcom61039.2024.10774028,https://doi.org/10.1109/MILCOM61039.2024.10774028,NaN,NaN,NaN
165,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",-,NaN,10.1109/milcom61039.2024.10774028,-,NaN,NaN,NaN
187,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, Gabriele...",-,NaN,10.23919/eucap60739.2024.10501539,-,NaN,NaN,NaN
188,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, G. Grado...",2024,European Conference on Antennas and Propagation,10.23919/eucap60739.2024.10501539,https://doi.org/10.23919/EuCAP60739.2024.10501539,NaN,NaN,NaN
208,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,NaN,10.1109/tvt.2023.3343379,-,NaN,NaN,NaN
209,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3343379,https://doi.org/10.1109/TVT.2023.3343379,NaN,NaN,NaN
297,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",2024,IEEE Wireless Communications Letters,10.1109/lwc.2023.3327360,https://doi.org/10.1109/LWC.2023.3327360,NaN,NaN,NaN
298,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",-,NaN,10.1109/lwc.2023.3327360,-,NaN,NaN,NaN
299,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Yongqing Xu, Yong Li, J Andrew Zhang, Marco Di...",2023,NaN,10.1109/TVT.2022.3197448,-,NaN,NaN,NaN
300,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Graduate Student Member Ieee Yongqing Xu, Memb...",2023,IEEE Transactions on Communications,10.1109/TVT.2022.3197448,https://doi.org/10.1109/TCOMM.2023.3344143,NaN,NaN,NaN
312,rec_00111,Joint Localization and Information Transfer fo...,"Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo",2022,Global Communications Conference,10.1109/globecom48099.2022.10001508,https://doi.org/10.1109/GLOBECOM48099.2022.100...,NaN,NaN,NaN
313,rec_00111,Joint Localization and Information Transfer fo...,"Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco D...",-,NaN,10.1109/globecom48099.2022.10001508,-,NaN,NaN,NaN
321,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",2024,IEEE Wireless Communications Letters,10.1109/lwc.2024.3365809,https://doi.org/10.1109/LWC.2024.3365809,NaN,NaN,NaN
322,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",-,NaN,10.1109/lwc.2024.3365809,-,NaN,NaN,NaN
336,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,2022,IEEE Communications Letters,10.1109/lcomm.2022.3195062,https://doi.org/10.1109/LCOMM.2022.3195062,NaN,NaN,NaN
337,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,-,NaN,10.1109/lcomm.2022.3195062,-,NaN,NaN,NaN
385,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, X...",-,NaN,10.1109/tvt.2023.3324448,-,NaN,NaN,NaN
386,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yuan Cheng, Jianhe Du, Jianbo Liu, Libiao Jin,...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3324448,https://doi.org/10.1109/TVT.2023.3324448,NaN,NaN,NaN
389,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
390,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
402,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
403,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
404,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bin Zhu",2024,IEEE Transactions on Wireless Communications,10.48550/arXiv.2305.04395,https://doi.org/10.1109/TWC.2024.3484569,NaN,NaN,NaN
406,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,2024 IEEE International Conference on Communic...,10.48550/arXiv.2305.04395,https://doi.org/10.1109/ICCWorkshops59551.2024...,NaN,NaN,NaN
407,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
408,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2023,IEEE Internet of Things Magazine,10.48550/arXiv.2305.04395,https://doi.org/10.1109/IOTM.001.2300196,NaN,NaN,NaN
409,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
445,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhong...",2023,IEEE Journal of Selected Topics in Quantum Ele...,10.1109/jstqe.2023.3276903,https://doi.org/10.1109/JSTQE.2023.3276903,NaN,NaN,NaN
446,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Zh...",-,NaN,10.1109/jstqe.2023.3276903,-,NaN,NaN,NaN
465,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yua...",2024,IEEE Internet of Things Journal,10.1109/jiot.2024.3397736,https://doi.org/10.1109/JIOT.2024.3397736,NaN,NaN,NaN
466,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan ...",-,NaN,10.1109/jiot.2024.3397736,-,NaN,NaN,NaN
470,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",2024,2024 4th International Conference on Neural Ne...,10.1109/nnice61279.2024.10498998,https://doi.org/10.1109/NNICE61279.2024.10498998,NaN,NaN,NaN
471,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",-,NaN,10.1109/nnice61279.2024.10498998,-,NaN,NaN,NaN
579,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, Octavia A Dobre, Ge...",2024,NaN,10.1109/twc.2023.3302319,-,NaN,NaN,NaN
580,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, O. Dobre, Geoffrey ...",2023,IEEE Transactions on Wireless Communications,10.1109/twc.2023.3302319,https://doi.org/10.1109/TWC.2023.3302319,NaN,NaN,NaN
637,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoch...",2025,NaN,10.1109/tvt.2024.3517709,-,NaN,NaN,NaN
638,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zhang, Tianqi Mao, Rui Na, Zhao...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2024.3517709,https://doi.org/10.1109/TVT.2024.3517709,NaN,NaN,NaN

# INCLUDED PART

In [57]:
# Temizlenmiş screening veri setindeki tüm benzersiz record_id'leri al
# Bu, screening.py dosyanızdaki son işlemden sonraki screening dataframe'i olmalı
cleaned_screening_ids = screening['record_id'].unique()

# included veri setini, sadece cleaned_screening_ids içinde olan record_id'lere göre filtrele
included_updated = included[included['record_id'].isin(cleaned_screening_ids)].copy()

print(f"included veri seti, screening'deki benzersiz record_id'lerle güncellendi.")
print(f"Yeni included veri setinde {len(included_updated)} kayıt bulunmaktadır.")

# Güncellenmiş included veri setini bir değişkene atayın veya bir dosyaya kaydedin
# Örneğin, included = included_updated diyerek bir sonraki adımlara geçebilirsiniz
# included_updated.to_csv('data/included_studies_updated.csv', index=False)

included veri seti, screening'deki benzersiz record_id'lerle güncellendi.
Yeni included veri setinde 658 kayıt bulunmaktadır.

In [58]:
import pandas as pd
from IPython.display import display

print("=== AYNI RECORD_ID, FARKLI TITLE KONTROLÜ ===")

# included_updated veri setini 'record_id'ye göre grupluyoruz.
# Ardından, 'title' sütunundaki benzersiz eleman sayısının 1'den fazla olduğu grupları filtreliyoruz.
same_id_diff_title = included_updated.groupby('record_id').filter(lambda x: len(x['title'].unique()) > 1)

# Bulunan kayıt sayısını ekrana yazdırıyoruz.
print(f"Toplam {len(same_id_diff_title)} kayıt bulundu.")

# Problemli kayıtların ham verisini gösteriyoruz.
display(same_id_diff_title)

print("\n" + "="*80 + "\n")

# --- Detaylı Analiz ---
# Bulduğumuz problemli kayıtları daha anlaşılır bir tabloya dönüştürüyoruz.
print("=== DETAYLI ANALİZ: FARKLI BAŞLIKLAR ===")

grouped_analysis = same_id_diff_title.groupby('record_id').agg(
    titles=('title', list),         # Aynı ID'ye ait tüm başlıkları liste olarak topluyoruz.
    authors=('authors', list),      # Aynı ID'ye ait tüm yazarları liste olarak topluyoruz.
    record_count=('record_id', 'count') # Her ID'nin kaç kez tekrar ettiğini sayıyoruz.
).reset_index()

# Analiz tablosunu ekrana basıyoruz.
display(grouped_analysis)

=== AYNI RECORD_ID, FARKLI TITLE KONTROLÜ ===
Toplam 62 kayıt bulundu.

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN
5,rec_00033,A Beam-Scannable Photonic THz-ISAC System Base...,"Z. Lyu, Lu Zhang, Hongqi Zhang, Zuomin Yang, H...",2023,2023 Asia Communications and Photonics Confere...,10.1109/acp/poem59049.2023.10368958,https://doi.org/10.1109/ACP/POEM59049.2023.103...,NaN,NaN,NaN
13,rec_00372,A Multi-Functional Reconfigurable Intelligent ...,"M. B. Sahin, O. Civi",2024,2024 IEEE International Symposium on Antennas ...,10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1109/AP-S/INC-USNC-URSI5205...,NaN,NaN,NaN
21,rec_00372,A reconfigurable intelligent surface with inte...,"Idban Alamzadeh, G. C. Alexandropoulos, Nir Sh...",2021,Scientific Reports,10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1038/s41598-021-99722-x,NaN,NaN,NaN
38,rec_00094,A Unified Waveform for Optical Wireless Integr...,"Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao,...",-,NaN,10.1109/acp55869.2022.10088865,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
595,rec_00567,STAR-RIS Aided Secure NOMA Integrated Sensing ...,"Wenjing Wei, Xiaowei Pang, Chengwen Xing, Nan ...",2024,IEEE Transactions on Wireless Communications,10.1109/WCCCT65447.2025.11027959,https://doi.org/10.1109/TWC.2024.3374728,NaN,NaN,NaN
605,rec_00678,STARS Enabled Full-Space Integrated Sensing an...,"Zheng Zhang, Mohsen Khalily, Mahtab Mirmohseni...",2023,2023 International Conference on Ubiquitous Co...,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/Ucom59132.2023.10257580,NaN,NaN,NaN
606,rec_00678,STARS Enabled Integrated Sensing and Communica...,"Zhao-Jie Wang, Xidong Mu, Yuanwei Liu",2022,IEEE Transactions on Wireless Communications,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/TWC.2023.3245297,NaN,NaN,NaN
639,rec_00521,Transmit Power Minimization for Double-RIS-Ena...,"Qi Zhang, Hongyi Bian, Yu Yao, Yongpeng Wu, Fe...",2024,International Conference on Innovative Computi...,10.1109/ICCC62479.2024.10681845,https://doi.org/10.1109/ICCC62479.2024.10681845,NaN,NaN,NaN
640,rec_00521,Transmit Power Minimization for Double-RIS-Ena...,"Qi Zhang, Wenqi Xiao, Pengcheng Zhu, Yu Yao, W...",-,NaN,10.1109/ICCC62479.2024.10681845,-,NaN,NaN,NaN

================================================================================

=== DETAYLI ANALİZ: FARKLI BAŞLIKLAR ===

,record_id,titles,authors,record_count
0,rec_00033,[A Beam-scannable photonic THz-ISAC system bas...,"[Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Y...",2
1,rec_00094,[A Unified Waveform for Optical Wireless Integ...,"[Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao...",2
2,rec_00105,[RIS-assisted Integrated Sensing and Communica...,"[Xiao Meng, Fan Liu, Shihang Lu, Sundeep Prabh...",2
3,rec_00199,[Joint beamforming and UAV trajectory optimiza...,"[Dan Deng, Wen Zhou, Xingwang Li, Daniel Benev...",2
4,rec_00214,[Optical reconfigurable intelligent surfaces a...,"[Haibo Wang, Zaichen Zhang, Bingcheng Zhu, Jia...",2
5,rec_00263,[Joint Beamforming Design for RIS-Assisted Int...,"[H. Luo, Rang Liu, Ming Li, Yang Liu, Qian Liu...",3
6,rec_00269,[Beamforming in Integrated Sensing and Communi...,"[Student Member Ieee R.S. Prasobh Sankar, Memb...",2
7,rec_00270,[Joint Active and Passive Beamforming Design f...,"[Zhe Xing, Rui Wang, Xiaojun Yuan, Zhe Xing, R...",2
8,rec_00319,[Joint Beamforming and Power Allocation for RI...,"[Yuanchen Guo, Yang Liu, Qing-He Wu, Xiaoyang ...",2
9,rec_00326,[Active RIS-Assisted Integrated Sensing and Co...,"[Yuantong Zhang, Junzhe Lin, Yifeng Zhao, Lian...",2
10,rec_00372,[A Multi-Functional Reconfigurable Intelligent...,"[M. B. Sahin, O. Civi, Idban Alamzadeh, G. C. ...",2
11,rec_00392,[Multi-IRS-Enabled Integrated Sensing and Comm...,"[Yuan Fang, Siyao Zhang, Xinmin Li, Jie Xu, Sh...",2
12,rec_00401,[CRB Minimization for RIS-Aided mmWave Integra...,"[Wanting Lyu, Songjie Yang, Yue Xiu, Ya Li, Ho...",2
13,rec_00408,[Optical Integrated Sensing and Communication ...,"[Shengqian Wang, Henry Chen, Haibo Wang, Zaich...",12
14,rec_00428,[RIS-Assisted Integrated Sensing and Symbiotic...,"[Bin Lyu, Haofan Du, Meng Hua, Changsheng You,...",2
15,rec_00429,"[Backscatter-Enabled RIS-Assisted NOMA ISAC, D...","[Faraz Nassar, Keshav Singh, S. Prakriya, S. S...",3
16,rec_00469,[Holographic Integrated Sensing and Communicat...,"[Marco Di Renzo, Haobo Zhang, Hongliang Zhang,...",2
17,rec_00496,[Integrated Localization and Communication for...,"[Xingyu Peng, Xiaoling Hu, Jiabao Gao, Richeng...",2
18,rec_00521,[Transmit Power Minimization for Double-RIS-En...,"[Qi Zhang, Hongyi Bian, Yu Yao, Yongpeng Wu, F...",2
19,rec_00567,[STAR-RIS Aided Secure Integrated Sensing and ...,"[Xuerong Zhao, Jiahui Hao, Gonghao Cui, Yongka...",2
20,rec_00670,[Deep Reinforcement Learning for Active RIS-As...,"[Bingxin Zhang, Kang Zheng, Chao Tong, Kun Yan...",2
21,rec_00671,[Active-RIS-Aided Covert Communications in NOM...,"[Miaomiao Zhu, Feng Lu, Xueyu Kang, Peng Chen,...",2
22,rec_00678,[STARS Enabled Full-Space Integrated Sensing a...,"[Zheng Zhang, Mohsen Khalily, Mahtab Mirmohsen...",2
23,rec_00744,[Holographic Beamforming for Integrated Sensin...,"[Shuhao Zeng, Haobo Zhang, Boya Di, Hongliang ...",2
24,rec_00754,[Reconfigurable Intelligent Surface assisted I...,"[Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu,...",2

In [41]:
import pandas as pd
from IPython.display import display

# --- 1. Adım: Aynı record_id'ye sahip, farklı başlıklı kayıtları bulma ---
# Bu kod, veri setinizdeki (included) potansiyel hatalı girişleri filtreler.
print("=== 1) AYNI RECORD_ID, FARKLI TITLE ===")
same_id_diff_title = included.groupby('record_id').filter(lambda x: len(x['title'].unique()) > 1)
print(f"Toplam {len(same_id_diff_title)} kayıt bulundu.")
display(same_id_diff_title)
print("\n" + "="*80 + "\n")

# --- 2. Adım: Farklı başlıkların detaylı analizi ---
# Bu adım, yukarıda bulunan kayıtları özetleyerek daha anlaşılır hale getirir.
print("=== 2) FARKLI BAŞLIKLARIN DETAYLI ANALİZİ ===")

# 'record_id'ye göre grupla ve her bir grup için 'title' listesini oluştur.
grouped_titles = same_id_diff_title.groupby('record_id').agg(
    titles_list=('title', list),
    authors_list=('authors', list)
).reset_index()

# Her bir 'record_id' için kaç farklı başlık olduğunu gösteren yeni bir sütun ekle.
grouped_titles['title_count'] = grouped_titles['titles_list'].apply(len)

# Analiz tablosunu göster.
display(grouped_titles)

=== 1) AYNI RECORD_ID, FARKLI TITLE ===
Toplam 62 kayıt bulundu.

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN
5,rec_00033,A Beam-Scannable Photonic THz-ISAC System Base...,"Z. Lyu, Lu Zhang, Hongqi Zhang, Zuomin Yang, H...",2023,2023 Asia Communications and Photonics Confere...,10.1109/acp/poem59049.2023.10368958,https://doi.org/10.1109/ACP/POEM59049.2023.103...,NaN,NaN,NaN
13,rec_00372,A Multi-Functional Reconfigurable Intelligent ...,"M. B. Sahin, O. Civi",2024,2024 IEEE International Symposium on Antennas ...,10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1109/AP-S/INC-USNC-URSI5205...,NaN,NaN,NaN
21,rec_00372,A reconfigurable intelligent surface with inte...,"Idban Alamzadeh, G. C. Alexandropoulos, Nir Sh...",2021,Scientific Reports,10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1038/s41598-021-99722-x,NaN,NaN,NaN
38,rec_00094,A Unified Waveform for Optical Wireless Integr...,"Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao,...",-,NaN,10.1109/acp55869.2022.10088865,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
595,rec_00567,STAR-RIS Aided Secure NOMA Integrated Sensing ...,"Wenjing Wei, Xiaowei Pang, Chengwen Xing, Nan ...",2024,IEEE Transactions on Wireless Communications,10.1109/WCCCT65447.2025.11027959,https://doi.org/10.1109/TWC.2024.3374728,NaN,NaN,NaN
605,rec_00678,STARS Enabled Full-Space Integrated Sensing an...,"Zheng Zhang, Mohsen Khalily, Mahtab Mirmohseni...",2023,2023 International Conference on Ubiquitous Co...,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/Ucom59132.2023.10257580,NaN,NaN,NaN
606,rec_00678,STARS Enabled Integrated Sensing and Communica...,"Zhao-Jie Wang, Xidong Mu, Yuanwei Liu",2022,IEEE Transactions on Wireless Communications,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/TWC.2023.3245297,NaN,NaN,NaN
639,rec_00521,Transmit Power Minimization for Double-RIS-Ena...,"Qi Zhang, Hongyi Bian, Yu Yao, Yongpeng Wu, Fe...",2024,International Conference on Innovative Computi...,10.1109/ICCC62479.2024.10681845,https://doi.org/10.1109/ICCC62479.2024.10681845,NaN,NaN,NaN
640,rec_00521,Transmit Power Minimization for Double-RIS-Ena...,"Qi Zhang, Wenqi Xiao, Pengcheng Zhu, Yu Yao, W...",-,NaN,10.1109/ICCC62479.2024.10681845,-,NaN,NaN,NaN

================================================================================

=== 2) FARKLI BAŞLIKLARIN DETAYLI ANALİZİ ===

,record_id,titles_list,authors_list,title_count
0,rec_00033,[A Beam-scannable photonic THz-ISAC system bas...,"[Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Y...",2
1,rec_00094,[A Unified Waveform for Optical Wireless Integ...,"[Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao...",2
2,rec_00105,[RIS-assisted Integrated Sensing and Communica...,"[Xiao Meng, Fan Liu, Shihang Lu, Sundeep Prabh...",2
3,rec_00199,[Joint beamforming and UAV trajectory optimiza...,"[Dan Deng, Wen Zhou, Xingwang Li, Daniel Benev...",2
4,rec_00214,[Optical reconfigurable intelligent surfaces a...,"[Haibo Wang, Zaichen Zhang, Bingcheng Zhu, Jia...",2
5,rec_00263,[Joint Beamforming Design for RIS-Assisted Int...,"[H. Luo, Rang Liu, Ming Li, Yang Liu, Qian Liu...",3
6,rec_00269,[Beamforming in Integrated Sensing and Communi...,"[Student Member Ieee R.S. Prasobh Sankar, Memb...",2
7,rec_00270,[Joint Active and Passive Beamforming Design f...,"[Zhe Xing, Rui Wang, Xiaojun Yuan, Zhe Xing, R...",2
8,rec_00319,[Joint Beamforming and Power Allocation for RI...,"[Yuanchen Guo, Yang Liu, Qing-He Wu, Xiaoyang ...",2
9,rec_00326,[Active RIS-Assisted Integrated Sensing and Co...,"[Yuantong Zhang, Junzhe Lin, Yifeng Zhao, Lian...",2
10,rec_00372,[A Multi-Functional Reconfigurable Intelligent...,"[M. B. Sahin, O. Civi, Idban Alamzadeh, G. C. ...",2
11,rec_00392,[Multi-IRS-Enabled Integrated Sensing and Comm...,"[Yuan Fang, Siyao Zhang, Xinmin Li, Jie Xu, Sh...",2
12,rec_00401,[CRB Minimization for RIS-Aided mmWave Integra...,"[Wanting Lyu, Songjie Yang, Yue Xiu, Ya Li, Ho...",2
13,rec_00408,[Optical Integrated Sensing and Communication ...,"[Shengqian Wang, Henry Chen, Haibo Wang, Zaich...",12
14,rec_00428,[RIS-Assisted Integrated Sensing and Symbiotic...,"[Bin Lyu, Haofan Du, Meng Hua, Changsheng You,...",2
15,rec_00429,"[Backscatter-Enabled RIS-Assisted NOMA ISAC, D...","[Faraz Nassar, Keshav Singh, S. Prakriya, S. S...",3
16,rec_00469,[Holographic Integrated Sensing and Communicat...,"[Marco Di Renzo, Haobo Zhang, Hongliang Zhang,...",2
17,rec_00496,[Integrated Localization and Communication for...,"[Xingyu Peng, Xiaoling Hu, Jiabao Gao, Richeng...",2
18,rec_00521,[Transmit Power Minimization for Double-RIS-En...,"[Qi Zhang, Hongyi Bian, Yu Yao, Yongpeng Wu, F...",2
19,rec_00567,[STAR-RIS Aided Secure Integrated Sensing and ...,"[Xuerong Zhao, Jiahui Hao, Gonghao Cui, Yongka...",2
20,rec_00670,[Deep Reinforcement Learning for Active RIS-As...,"[Bingxin Zhang, Kang Zheng, Chao Tong, Kun Yan...",2
21,rec_00671,[Active-RIS-Aided Covert Communications in NOM...,"[Miaomiao Zhu, Feng Lu, Xueyu Kang, Peng Chen,...",2
22,rec_00678,[STARS Enabled Full-Space Integrated Sensing a...,"[Zheng Zhang, Mohsen Khalily, Mahtab Mirmohsen...",2
23,rec_00744,[Holographic Beamforming for Integrated Sensin...,"[Shuhao Zeng, Haobo Zhang, Boya Di, Hongliang ...",2
24,rec_00754,[Reconfigurable Intelligent Surface assisted I...,"[Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu,...",2

In [42]:
import pandas as pd
from IPython.display import display

print("=== 1) AYNI RECORD_ID, AYNI TITLE - HAM VERİ ===")
# 'record_id' ve 'title' sütunlarını kullanarak tam kopyaları bulur.
# 'keep=False' parametresi, tüm kopyaları (hem ilk hem de sonraki tekrar edenleri) gösterir.
same_id_same_title = included[included.duplicated(subset=['record_id', 'title'], keep=False)]
print(f"Toplam {len(same_id_same_title)} kayıt bulundu.")
display(same_id_same_title)
print("\n" + "="*80 + "\n")

=== 1) AYNI RECORD_ID, AYNI TITLE - HAM VERİ ===
Toplam 41 kayıt bulundu.

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
27,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2024,NaN,10.1109/tits.2023.3330172,-,NaN,NaN,NaN
28,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2022,IEEE transactions on intelligent transportatio...,10.1109/tits.2023.3330172,https://doi.org/10.1109/TITS.2023.3330172,NaN,NaN,NaN
83,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R. Sankar, S. Chepuri",2022,European Signal Processing Conference,10.23919/eusipco55093.2022.9909562,https://doi.org/10.48550/arXiv.2203.05902,NaN,NaN,NaN
84,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R S Prasobh Sankar, Sundeep Prabhakar Chepuri",-,NaN,10.23919/eusipco55093.2022.9909562,-,NaN,NaN,NaN
164,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",2024,IEEE Military Communications Conference,10.1109/milcom61039.2024.10774028,https://doi.org/10.1109/MILCOM61039.2024.10774028,NaN,NaN,NaN
165,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",-,NaN,10.1109/milcom61039.2024.10774028,-,NaN,NaN,NaN
187,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, Gabriele...",-,NaN,10.23919/eucap60739.2024.10501539,-,NaN,NaN,NaN
188,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, G. Grado...",2024,European Conference on Antennas and Propagation,10.23919/eucap60739.2024.10501539,https://doi.org/10.23919/EuCAP60739.2024.10501539,NaN,NaN,NaN
208,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,NaN,10.1109/tvt.2023.3343379,-,NaN,NaN,NaN
209,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3343379,https://doi.org/10.1109/TVT.2023.3343379,NaN,NaN,NaN
297,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",2024,IEEE Wireless Communications Letters,10.1109/lwc.2023.3327360,https://doi.org/10.1109/LWC.2023.3327360,NaN,NaN,NaN
298,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",-,NaN,10.1109/lwc.2023.3327360,-,NaN,NaN,NaN
299,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Yongqing Xu, Yong Li, J Andrew Zhang, Marco Di...",2023,NaN,10.1109/TVT.2022.3197448,-,NaN,NaN,NaN
300,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Graduate Student Member Ieee Yongqing Xu, Memb...",2023,IEEE Transactions on Communications,10.1109/TVT.2022.3197448,https://doi.org/10.1109/TCOMM.2023.3344143,NaN,NaN,NaN
312,rec_00111,Joint Localization and Information Transfer fo...,"Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo",2022,Global Communications Conference,10.1109/globecom48099.2022.10001508,https://doi.org/10.1109/GLOBECOM48099.2022.100...,NaN,NaN,NaN
313,rec_00111,Joint Localization and Information Transfer fo...,"Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco D...",-,NaN,10.1109/globecom48099.2022.10001508,-,NaN,NaN,NaN
321,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",2024,IEEE Wireless Communications Letters,10.1109/lwc.2024.3365809,https://doi.org/10.1109/LWC.2024.3365809,NaN,NaN,NaN
322,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",-,NaN,10.1109/lwc.2024.3365809,-,NaN,NaN,NaN
336,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,2022,IEEE Communications Letters,10.1109/lcomm.2022.3195062,https://doi.org/10.1109/LCOMM.2022.3195062,NaN,NaN,NaN
337,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,-,NaN,10.1109/lcomm.2022.3195062,-,NaN,NaN,NaN
385,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, X...",-,NaN,10.1109/tvt.2023.3324448,-,NaN,NaN,NaN
386,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yuan Cheng, Jianhe Du, Jianbo Liu, Libiao Jin,...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3324448,https://doi.org/10.1109/TVT.2023.3324448,NaN,NaN,NaN
389,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
390,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
402,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
403,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
404,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bin Zhu",2024,IEEE Transactions on Wireless Communications,10.48550/arXiv.2305.04395,https://doi.org/10.1109/TWC.2024.3484569,NaN,NaN,NaN
406,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,2024 IEEE International Conference on Communic...,10.48550/arXiv.2305.04395,https://doi.org/10.1109/ICCWorkshops59551.2024...,NaN,NaN,NaN
407,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
408,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2023,IEEE Internet of Things Magazine,10.48550/arXiv.2305.04395,https://doi.org/10.1109/IOTM.001.2300196,NaN,NaN,NaN
409,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
445,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhong...",2023,IEEE Journal of Selected Topics in Quantum Ele...,10.1109/jstqe.2023.3276903,https://doi.org/10.1109/JSTQE.2023.3276903,NaN,NaN,NaN
446,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Zh...",-,NaN,10.1109/jstqe.2023.3276903,-,NaN,NaN,NaN
465,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yua...",2024,IEEE Internet of Things Journal,10.1109/jiot.2024.3397736,https://doi.org/10.1109/JIOT.2024.3397736,NaN,NaN,NaN
466,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan ...",-,NaN,10.1109/jiot.2024.3397736,-,NaN,NaN,NaN
470,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",2024,2024 4th International Conference on Neural Ne...,10.1109/nnice61279.2024.10498998,https://doi.org/10.1109/NNICE61279.2024.10498998,NaN,NaN,NaN
471,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",-,NaN,10.1109/nnice61279.2024.10498998,-,NaN,NaN,NaN
579,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, Octavia A Dobre, Ge...",2024,NaN,10.1109/twc.2023.3302319,-,NaN,NaN,NaN
580,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, O. Dobre, Geoffrey ...",2023,IEEE Transactions on Wireless Communications,10.1109/twc.2023.3302319,https://doi.org/10.1109/TWC.2023.3302319,NaN,NaN,NaN
637,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoch...",2025,NaN,10.1109/tvt.2024.3517709,-,NaN,NaN,NaN
638,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zhang, Tianqi Mao, Rui Na, Zhao...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2024.3517709,https://doi.org/10.1109/TVT.2024.3517709,NaN,NaN,NaN

================================================================================

In [43]:
print("=== 2) DUPLİKE KAYITLARIN ANALİZİ ===")

# Bulunan kopyaları 'record_id' ve 'title'a göre gruplayıp analiz eder.
grouped_duplicates = same_id_same_title.groupby(['record_id', 'title']).agg(
    authors_list=('authors', list),
    count=('record_id', 'count')
).reset_index()

# Sadece 2'den fazla tekrar edenleri göstermek için filtreleme yapabilirsiniz (isteğe bağlı).
# grouped_duplicates = grouped_duplicates[grouped_duplicates['count'] > 1]

# Analiz tablosunu gösterir.
display(grouped_duplicates)

=== 2) DUPLİKE KAYITLARIN ANALİZİ ===

,record_id,title,authors_list,count
0,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,"[Hongliang Zhang, Hongliang Zhang]",2
1,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"[Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhan...",2
2,rec_00054,Joint Resource Allocation and Reflecting Preco...,"[Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sh...",2
3,rec_00078,Recent advances in integrated sensing and comm...,"[Yufeng Zhang, Minglun Zhang, Yufeng Zhang, Mi...",2
4,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"[Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhon...",2
5,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"[Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, ...",2
6,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"[Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Y...",2
7,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"[Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yan...",2
8,rec_00104,Simultaneous Beam Training and Target Sensing ...,"[Kangjian Chen, Chenhao Qi, Octavia A Dobre, G...",2
9,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"[Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoc...",2
10,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"[Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yu...",2
11,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"[Hamidreza Taghvaee, Maryam Khodadadi, Gabriel...",2
12,rec_00111,Joint Localization and Information Transfer fo...,"[Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo,...",2
13,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"[Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, ...",2
14,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"[R. Sankar, S. Chepuri, R S Prasobh Sankar, Su...",2
15,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"[Yongqing Xu, Yong Li, J Andrew Zhang, Marco D...",2
16,rec_00408,Optical Integrated Sensing and Communication S...,"[Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingc...",3
17,rec_00408,Optical Integrated Sensing and Communication w...,"[Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, ...",2
18,rec_00408,Optical Integrated Sensing and Communication: ...,"[Yunfeng Wen, Fang Yang, Jian Song, Zhu Han, Y...",2

In [45]:
import pandas as pd
from IPython.display import display

print("=== 1) FARKLI RECORD_ID, AYNI TITLE - HAM VERİ ===")
# 'title' sütununa göre grupla ve 'record_id'lerin benzersiz sayısının 1'den fazla olduğu grupları filtrele.
diff_id_same_title = included.groupby('title').filter(lambda x: len(x['record_id'].unique()) > 1)
print(f"Toplam {len(diff_id_same_title)} kayıt bulundu.")
display(diff_id_same_title)
print("\n" + "="*80 + "\n")

=== 1) FARKLI RECORD_ID, AYNI TITLE - HAM VERİ ===
Toplam 0 kayıt bulundu.

Empty DataFrame
Columns: [record_id, title, authors, year, venue, doi, url, citation, pub_type, peer_reviewed]
Index: []

================================================================================

In [46]:
print("=== 2) DUPLİKE BAŞLIKLARIN ANALİZİ ===")

# Bulunan yinelenen başlıkları 'title'a göre gruplayıp analiz eder.
grouped_duplicates = diff_id_same_title.groupby('title').agg(
    record_ids=('record_id', list),     # Tüm 'record_id'leri liste olarak topla.
    authors_list=('authors', list)        # Tüm 'authors'ları liste olarak topla.
).reset_index()

# Her bir başlığın kaç kez tekrar ettiğini gösteren yeni bir sütun ekle.
grouped_duplicates['repeat_count'] = grouped_duplicates['record_ids'].apply(len)

# Analiz tablosunu gösterir.
display(grouped_duplicates)

=== 2) DUPLİKE BAŞLIKLARIN ANALİZİ ===

Empty DataFrame
Columns: [title, record_ids, authors_list, repeat_count]
Index: []

# SCREENING PART

In [47]:
screening = pd.read_csv('data/screening_log.csv')

In [48]:
# 1) aynı record_id, farklı title
print("=== 1) AYNI RECORD_ID, FARKLI TITLE ===")
same_id_diff_title = screening.groupby('record_id').filter(lambda x: len(set(x['title'])) > 1)
print(f"Toplam {len(same_id_diff_title)} kayıt bulundu")
display(same_id_diff_title)

print("\n" + "="*80 + "\n")

=== 1) AYNI RECORD_ID, FARKLI TITLE ===
Toplam 0 kayıt bulundu

Empty DataFrame
Columns: [record_id, source_db, status, decided_by, decided_at, stage, decision, automation_flag, title, authors, doi_or_id, year, screening_score]
Index: []

================================================================================

In [49]:
# 2) aynı record_id, aynı title
print("=== 2) AYNI RECORD_ID, AYNI TITLE ===")
same_id_same_title = screening[screening.duplicated(subset=['record_id', 'title'], keep=False)]
print(f"Toplam {len(same_id_same_title)} kayıt bulundu")
display(same_id_same_title)

print("\n" + "="*80 + "\n")

=== 2) AYNI RECORD_ID, AYNI TITLE ===
Toplam 0 kayıt bulundu

Empty DataFrame
Columns: [record_id, source_db, status, decided_by, decided_at, stage, decision, automation_flag, title, authors, doi_or_id, year, screening_score]
Index: []

================================================================================

In [50]:
# 4) farklı record_id, farklı title
print("=== 4) FARKLI RECORD_ID, FARKLI TITLE ===")
unique_pairs = screening.drop_duplicates(subset=['record_id', 'title'], keep=False)
print(f"Toplam {len(unique_pairs)} benzersiz kayıt bulundu")
display(unique_pairs)

print("\n" + "="*80 + "\n")

=== 4) FARKLI RECORD_ID, FARKLI TITLE ===
Toplam 757 benzersiz kayıt bulundu

,record_id,source_db,status,decided_by,decided_at,stage,decision,automation_flag,title,authors,doi_or_id,year,screening_score
0,rec_00001,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Joint Beamforming and Power Control for D2D-As...,"Zhenyu Xue, Yuang Chen, Hancheng Lu, Baolin Ch...",10.1109/globecom52923.2024.10901750,-,2.5
1,rec_00002,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Integrated Sensing and Communications With Mix...,"Yun Xiao, Enhao Wa, Yunfei Chen, Li Chen, Aiss...",10.1109/lwc.2024.3521186,-,2.7
2,rec_00003,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,"Waveform Design for Integrated Radar, Communic...","Qi Cheng, Yanjie Ji, Xuezhou Yang, Li Zhou, Ju...",10.1109/icwoc65853.2025.11151123,-,2.7
3,rec_00004,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Precoding for Multi-Cell ISAC: From Coordinate...,"Nithin Babu, Christos Masouros, Constantinos B...",10.1109/twc.2024.3417713,2024,2.5
4,rec_00005,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,SDOA-Net: An Efficient Deep-Learning-Based DOA...,"Peng Chen, Zhimin Chen, Liang Liu, Yun Chen, X...",10.1109/tim.2024.3391338,-,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,rec_00753,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Algorithm Design and Prototype Validation for ...,"Cheng Luo, Luping Xiang, Jie Hu, Kun Yang",10.1109/twc.2025.3599545,2025,2.7
753,rec_00754,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Reconfigurable Intelligent Surface assisted In...,"Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu, ...",10.1109/icasspw62465.2024.10626004,-,2.7
754,rec_00755,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Performance of Massive MIMO aided by Reflectiv...,"André Flaiban, André Flaiban, Taufik Abrão",10.1007/s10922-024-09846-4,-,2.5
755,R002,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474334Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN
756,R004,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474612Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [56]:
import pandas as pd
from IPython.display import display

# --- 1. Adım: Farklı ID'lere sahip, aynı başlıklı kayıtları bulma ---
print("=== 1) FARKLI RECORD_ID, AYNI TITLE ===")
diff_id_same_title = screening.groupby('title').filter(lambda x: len(x['record_id'].unique()) > 1)
print(f"Toplam {len(diff_id_same_title)} kayıt bulundu.")
display(diff_id_same_title)
print("\n" + "="*80 + "\n")

# --- 2. Adım: Yinelenen başlıkları detaylı olarak gruplama ve analiz etme ---
print("=== 2) DUPLIKE BAŞLIKLARIN DETAYLI ANALİZİ ===")

grouped_duplicates = diff_id_same_title.groupby('title').agg(
    record_ids=('record_id', list),
    authors_list=('authors', list)
).reset_index()

grouped_duplicates['repeat_count'] = grouped_duplicates['record_ids'].apply(len)

display(grouped_duplicates)

# --- 3. Adım: Analiz tablosunu CSV dosyasına kaydetme ---
# Oluşturulan `grouped_duplicates` DataFrame'ini bir CSV dosyasına kaydeder.
# 'index=False' parametresi, Pandas indeks numarasının dosyaya yazılmasını engeller.
output_file = 'duplicate_titles_analysis.csv'
grouped_duplicates.to_csv(output_file, index=False)

print(f"\nAnaliz sonuçları '{output_file}' dosyasına başarıyla kaydedildi.");

=== 1) FARKLI RECORD_ID, AYNI TITLE ===
Toplam 0 kayıt bulundu.

Empty DataFrame
Columns: [record_id, source_db, status, decided_by, decided_at, stage, decision, automation_flag, title, authors, doi_or_id, year, screening_score]
Index: []

================================================================================

=== 2) DUPLIKE BAŞLIKLARIN DETAYLI ANALİZİ ===

Empty DataFrame
Columns: [title, record_ids, authors_list, repeat_count]
Index: []

Analiz sonuçları 'duplicate_titles_analysis.csv' dosyasına başarıyla kaydedildi.

In [53]:
# Farklı ID'lere sahip, aynı başlıklı kayıtları bul
diff_id_same_title = screening.groupby('title').filter(lambda x: len(x['record_id'].unique()) > 1)

# Bu kayıtların başlıklarını ve bunlara ait ID'leri bir sözlükte grupla
grouped_titles = diff_id_same_title.groupby('title')['record_id'].apply(list).to_dict()

# Düzeltme için bir kural belirle: Her grup için ilk record_id'yi doğru kabul et
# Diğer tüm record_id'leri bu ilk id ile değiştireceğiz
correction_map = {}
for title, ids in grouped_titles.items():
    primary_id = ids[0]
    for secondary_id in ids[1:]:
        correction_map[secondary_id] = primary_id

In [54]:
# screening DataFrame'indeki tüm record_id'leri correction_map'e göre güncelle
screening['record_id'] = screening['record_id'].replace(correction_map)

print("screenign veri setindeki 'record_id' duplikasyonları başarıyla düzeltildi.")

screenign veri setindeki 'record_id' duplikasyonları başarıyla düzeltildi.

In [55]:
# Düzeltme sonrası 'farklı ID, aynı title' durumunu tekrar kontrol et
print("\n=== DÜZELTME SONRASI KONTROL ===")
diff_id_same_title_after = screening.groupby('title').filter(lambda x: len(x['record_id'].unique()) > 1)

if diff_id_same_title_after.empty:
    print("Mükemmel! Artık 'farklı record_id, aynı title' problemi bulunmuyor.")
    # Bu aşamada, aynı ID, aynı başlık olan kayıtlar oluştuğu için
    # onları da temizlememiz gerekecek
    same_id_same_title = screening[screening.duplicated(subset=['record_id', 'title'], keep='first')]
    print(f"Düzeltme sonrası oluşan tam duplike kayıt sayısı: {len(same_id_same_title)}")
    
    # Tam duplikeleri kaldır
    screening.drop_duplicates(subset=['record_id', 'title'], keep='first', inplace=True)
    
    print("Tam duplike kayıtlar temizlendi. screening veri seti şimdi daha temiz.")
else:
    print("Hata! Bazı kayıtlar düzeltilemedi.")
    display(diff_id_same_title_after)

=== DÜZELTME SONRASI KONTROL ===
Mükemmel! Artık 'farklı record_id, aynı title' problemi bulunmuyor.
Düzeltme sonrası oluşan tam duplike kayıt sayısı: 22
Tam duplike kayıtlar temizlendi. screening veri seti şimdi daha temiz.

In [59]:
screening

,record_id,source_db,status,decided_by,decided_at,stage,decision,automation_flag,title,authors,doi_or_id,year,screening_score
0,rec_00001,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Joint Beamforming and Power Control for D2D-As...,"Zhenyu Xue, Yuang Chen, Hancheng Lu, Baolin Ch...",10.1109/globecom52923.2024.10901750,-,2.5
1,rec_00002,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Integrated Sensing and Communications With Mix...,"Yun Xiao, Enhao Wa, Yunfei Chen, Li Chen, Aiss...",10.1109/lwc.2024.3521186,-,2.7
2,rec_00003,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,"Waveform Design for Integrated Radar, Communic...","Qi Cheng, Yanjie Ji, Xuezhou Yang, Li Zhou, Ju...",10.1109/icwoc65853.2025.11151123,-,2.7
3,rec_00004,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Precoding for Multi-Cell ISAC: From Coordinate...,"Nithin Babu, Christos Masouros, Constantinos B...",10.1109/twc.2024.3417713,2024,2.5
4,rec_00005,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,SDOA-Net: An Efficient Deep-Learning-Based DOA...,"Peng Chen, Zhimin Chen, Liang Liu, Yun Chen, X...",10.1109/tim.2024.3391338,-,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,rec_00753,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Algorithm Design and Prototype Validation for ...,"Cheng Luo, Luping Xiang, Jie Hu, Kun Yang",10.1109/twc.2025.3599545,2025,2.7
753,rec_00754,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Reconfigurable Intelligent Surface assisted In...,"Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu, ...",10.1109/icasspw62465.2024.10626004,-,2.7
754,rec_00755,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Performance of Massive MIMO aided by Reflectiv...,"André Flaiban, André Flaiban, Taufik Abrão",10.1007/s10922-024-09846-4,-,2.5
755,R002,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474334Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN
756,R004,unknown,fulltext_excluded,consistency-fixer,2025-10-11T14:09:12.474612Z,fulltext,exclude,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
output_dir = 'data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"'{output_dir}' klasörü oluşturuldu.")

In [61]:
# 2. DataFrame'i belirtilen yola CSV olarak kaydet
file_path = os.path.join(output_dir, 'screening_log.csv')
screening.to_csv(file_path, index=False)

In [62]:
# Bu kodu çalıştırarak 'included' değişkeninin var olup olmadığını anla
try:
    print("'included' DataFrame'i mevcut. İşte ilk 5 satırı:")
    display(included.head())
except NameError:
    print("'included' adında bir DataFrame henüz oluşturulmamış veya mevcut değil.")

'included' DataFrame'i mevcut. İşte ilk 5 satırı:

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
0,rec_00702,1- bit Reconfigurable Intelligent Surface for ...,"Deepak, Akhila Gouda, Saptarshi Ghosh",2025,2025 Third International Conference on Microwa...,10.1109/MAC64480.2025.11140492,https://doi.org/10.1109/MAC64480.2025.11140492,NaN,NaN,NaN
1,rec_00158,1000-Channel Integrated Optical Phased Array w...,"Yong Liu, Xiansong Meng",-,NaN,arXiv:2508.19977,-,NaN,NaN,NaN
2,rec_00585,2-Bit RIS Prototyping Enhancing Rapid-Response...,"Yufei Zhao, Yuan Feng, Afkar Mohamed Ismail, Z...",2024,IEEE Open Journal of the Communications Society,10.1109/OJCOMS.2024.3439558,https://doi.org/10.1109/OJCOMS.2024.3439558,NaN,NaN,NaN
3,rec_00040,6G INTEGRATED SENSING AND COMMUNICATION -SENSI...,"Zhi Zhou, Xianjin Li, Jia He, Xiaoyan Bi, Yan ...",-,NaN,10.1109/icassp49357.2023.10096544,-,NaN,NaN,NaN
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN

In [63]:
import pandas as pd

# --- Adım 1: screening_log.csv dosyasını yükle ---
# Dosya yolunun doğru olduğundan emin ol
try:
    screening_log = pd.read_csv('data/screening_log.csv')
    print("screening_log.csv başarıyla yüklendi.")
    display(screening_log.head())
except FileNotFoundError:
    print("HATA: 'screening_log.csv' dosyası bulunamadı. Lütfen dosya yolunu kontrol et.")
    # Eğer dosya yoksa, aşağıdaki kod çalışmayacağı için işlemi burada durdurabiliriz.
    screening_log = None

# --- Adım 2: Çapraz Kontrolü Gerçekleştir ---
if screening_log is not None:
    # Günlük dosyasından "dahil edildi" olarak işaretlenenlerin ID'lerini al
    # !!! DİKKAT: 'status' ve 'included' değerlerini kendi verinize göre güncelleyin !!!
    try:
        supposed_to_be_included_ids = set(screening_log[screening_log['decision'] == 'Include']['record_id'])
        print(f"\nLog dosyasına göre dahil edilmesi gereken {len(supposed_to_be_included_ids)} adet kayıt var.")
    
        # Mevcut 'included' DataFrame'indeki ID'leri al
        # Bu DataFrame'in daha önceki adımlarda temizlendiğini varsayıyoruz.
        actually_included_ids = set(included['record_id'])
        print(f"Mevcut 'included' DataFrame'inde ise {len(actually_included_ids)} adet kayıt var.")
    
        print("\n" + "="*80 + "\n")
        print("Çapraz kontrol sonuçları:")
    
        # --- Kontrol 1: Log'da 'included' ama DataFrame'de YOK ---
        # Bunlar, dahil edilmesi gerekirken kaybolmuş olabilecek kayıtlardır.
        missing_from_df = supposed_to_be_included_ids - actually_included_ids
        if missing_from_df:
            print(f"\n[!] UYARI: Log'da 'included' olarak işaretli ama DataFrame'de bulunamayan {len(missing_from_df)} kayıt tespit edildi:")
            print(list(missing_from_df))
        else:
            print("\n[✓] Harika! Log'da 'included' olan tüm kayıtlar DataFrame'de mevcut.")
    
        # --- Kontrol 2: DataFrame'de VAR ama Log'da 'included' DEĞİL ---
        # Bunlar, yanlışlıkla dahil edilmiş olabilecek kayıtlardır.
        extra_in_df = actually_included_ids - supposed_to_be_included_ids
        if extra_in_df:
            print(f"\n[!] UYARI: DataFrame'de mevcut ama Log'da 'included' olarak işaretlenmemiş {len(extra_in_df)} kayıt tespit edildi:")
            print(list(extra_in_df))
        else:
            print("[✓] Harika! DataFrame'deki tüm kayıtlar Log dosyasında 'included' olarak doğrulanmıştır.")

    except KeyError as e:
        print(f"\n[HATA]: Kodda belirtilen bir sütun adı bulunamadı: {e}")
        print("Lütfen `screening_log` DataFrame'indeki 'status' ve 'record_id' gibi sütun adlarını kontrol edin.")

screening_log.csv başarıyla yüklendi.

,record_id,source_db,status,decided_by,decided_at,stage,decision,automation_flag,title,authors,doi_or_id,year,screening_score
0,rec_00001,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Joint Beamforming and Power Control for D2D-As...,"Zhenyu Xue, Yuang Chen, Hancheng Lu, Baolin Ch...",10.1109/globecom52923.2024.10901750,-,2.5
1,rec_00002,Elicit,screened,reviewer,2025-10-06 18:21:39.137537,tiab,Include,manual,Integrated Sensing and Communications With Mix...,"Yun Xiao, Enhao Wa, Yunfei Chen, Li Chen, Aiss...",10.1109/lwc.2024.3521186,-,2.7
2,rec_00003,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,"Waveform Design for Integrated Radar, Communic...","Qi Cheng, Yanjie Ji, Xuezhou Yang, Li Zhou, Ju...",10.1109/icwoc65853.2025.11151123,-,2.7
3,rec_00004,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,Precoding for Multi-Cell ISAC: From Coordinate...,"Nithin Babu, Christos Masouros, Constantinos B...",10.1109/twc.2024.3417713,2024,2.5
4,rec_00005,Elicit,completed,reviewer,2025-10-06 18:21:39.137537,screening,Include,manual,SDOA-Net: An Efficient Deep-Learning-Based DOA...,"Peng Chen, Zhimin Chen, Liang Liu, Yun Chen, X...",10.1109/tim.2024.3391338,-,2.5

Log dosyasına göre dahil edilmesi gereken 638 adet kayıt var.
Mevcut 'included' DataFrame'inde ise 607 adet kayıt var.

================================================================================

Çapraz kontrol sonuçları:

[!] UYARI: Log'da 'included' olarak işaretli ama DataFrame'de bulunamayan 34 kayıt tespit edildi:
['rec_00563', 'rec_00256', 'rec_00070', 'rec_00533', 'rec_00425', 'rec_00439', 'rec_00301', 'rec_00323', 'rec_00486', 'rec_00226', 'rec_00625', 'rec_00236', 'rec_00303', 'rec_00281', 'rec_00358', 'rec_00376', 'rec_00232', 'rec_00379', 'rec_00101', 'rec_00053', 'rec_00366', 'rec_00404', 'rec_00171', 'rec_00259', 'rec_00320', 'rec_00642', 'rec_00411', 'rec_00673', 'rec_00581', 'rec_00222', 'rec_00718', 'rec_00162', 'rec_00241', 'rec_00743']

[!] UYARI: DataFrame'de mevcut ama Log'da 'included' olarak işaretlenmemiş 3 kayıt tespit edildi:
['rec_00103', nan, 'rec_00118']

In [64]:
# Adım 1: Her bir record_id için kaç tane benzersiz başlık olduğunu say
id_to_title_counts = included.groupby('record_id')['title'].nunique()

# Adım 2: Birden fazla benzersiz başlığa sahip olan record_id'leri bul
conflicting_ids = id_to_title_counts[id_to_title_counts > 1].index.tolist()

if conflicting_ids:
    print(f"[!] UYARI: {len(conflicting_ids)} adet 'record_id' birden fazla farklı başlığa sahip. Bu ciddi bir tutarsızlık!")
    print("Çakışan kayıtlar aşağıda listelenmiştir:")
    
    # Çakışan kayıtların tamamını görmek için DataFrame'i filtrele
    conflicting_entries = included[included['record_id'].isin(conflicting_ids)].sort_values('record_id')
    display(conflicting_entries)
else:
    print("[✓] Harika! Her 'record_id' yalnızca tek bir benzersiz başlığa sahip. Veri bütünlüğü bu açıdan sağlam.")

[!] UYARI: 25 adet 'record_id' birden fazla farklı başlığa sahip. Bu ciddi bir tutarsızlık!
Çakışan kayıtlar aşağıda listelenmiştir:

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN
5,rec_00033,A Beam-Scannable Photonic THz-ISAC System Base...,"Z. Lyu, Lu Zhang, Hongqi Zhang, Zuomin Yang, H...",2023,2023 Asia Communications and Photonics Confere...,10.1109/acp/poem59049.2023.10368958,https://doi.org/10.1109/ACP/POEM59049.2023.103...,NaN,NaN,NaN
38,rec_00094,A Unified Waveform for Optical Wireless Integr...,"Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao,...",-,NaN,10.1109/acp55869.2022.10088865,-,NaN,NaN,NaN
400,rec_00094,Optical Integrated Sensing and Communication,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu",2023,arXiv.org,10.1109/acp55869.2022.10088865,https://doi.org/10.48550/arXiv.2305.04395,NaN,NaN,NaN
524,rec_00105,RIS-assisted Integrated Sensing and Communicat...,"Xiao Meng, F. Liu, Shih-Jung Lu, S. Chepuri, C...",2022,International Radar Conference,10.1109/radarconf2351548.2023.10149664,https://doi.org/10.1109/RadarConf2351548.2023....,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
606,rec_00678,STARS Enabled Integrated Sensing and Communica...,"Zhao-Jie Wang, Xidong Mu, Yuanwei Liu",2022,IEEE Transactions on Wireless Communications,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/TWC.2023.3245297,NaN,NaN,NaN
201,rec_00744,Holographic Beamforming for Integrated Sensing...,"Shuhao Zeng, Haobo Zhang, Boya Di, Hongliang Z...",2025,-,10.1109/jsac.2025.3612921,-,NaN,NaN,NaN
202,rec_00744,Holographic Integrated Sensing and Communication,"Haobo Zhang, Hongliang Zhang, Boya Di, M. D. R...",2022,IEEE Journal on Selected Areas in Communications,10.1109/jsac.2025.3612921,https://doi.org/10.1109/jsac.2022.3155548,NaN,NaN,NaN
478,rec_00754,Reconfigurable Intelligent Surface assisted In...,"Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu, ...",-,-,10.1109/icasspw62465.2024.10626004,-,NaN,NaN,NaN
479,rec_00754,Reconfigurable Intelligent Surface Assisted In...,"Jiahua Wan, Hong Ren, Cunhua Pan, Zhiyuan Yu, ...",2024,2024 IEEE International Conference on Acoustic...,10.1109/icasspw62465.2024.10626004,https://doi.org/10.1109/ICASSPW62465.2024.1062...,NaN,NaN,NaN

In [65]:
import pandas as pd

# --- KONTROL 1: AYNI ID, FARKLI BAŞLIK (EN KRİTİK HATA) ---
print("="*80)
print("KONTROL 1: Aynı 'record_id' için farklı 'title' var mı?")
print("="*80)
id_to_title_counts = included.groupby('record_id')['title'].nunique()
conflicting_ids = id_to_title_counts[id_to_title_counts > 1].index.tolist()

if conflicting_ids:
    print(f"[!] UYARI: {len(conflicting_ids)} adet 'record_id' birden fazla farklı başlığa sahip!")
    conflicting_entries = included[included['record_id'].isin(conflicting_ids)].sort_values('record_id')
    display(conflicting_entries)
else:
    print("[✓] Harika! Her 'record_id' yalnızca tek bir benzersiz başlığa sahip.")

# --- KONTROL 2: FARKLI ID, AYNI BAŞLIK (İÇERİK MÜKERRERLİĞİ) ---
print("\n" + "="*80)
print("KONTROL 2: Aynı 'title' için farklı 'record_id' var mı?")
print("="*80)
title_to_id_counts = included.groupby('title')['record_id'].nunique()
duplicate_titles = title_to_id_counts[title_to_id_counts > 1].index.tolist()

if duplicate_titles:
    print(f"[!] BİLGİ: {len(duplicate_titles)} adet başlık, birden fazla farklı 'record_id' ile eşleşiyor.")
    duplicate_content_entries = included[included['title'].isin(duplicate_titles)].sort_values('title')
    display(duplicate_content_entries)
else:
    print("[✓] Mükemmel! İçerik mükerrerliği görünmüyor.")

# --- KONTROL 3: AYNI ID, AYNI BAŞLIK (TAM MÜKERRERLİK) ---
print("\n" + "="*80)
print("KONTROL 3: Hem 'record_id' hem de 'title' aynı olan satırlar var mı?")
print("="*80)
full_duplicates = included[included.duplicated(subset=['record_id', 'title'], keep=False)]

if not full_duplicates.empty:
    print(f"[!] UYARI: {len(full_duplicates)} adet satır, hem 'record_id' hem de 'title' bazında tamamen mükerrer.")
    display(full_duplicates.sort_values('record_id'))
else:
    print("[✓] Çok iyi! 'record_id' ve 'title' bazında tam mükerrer satır yok.")

================================================================================
KONTROL 1: Aynı 'record_id' için farklı 'title' var mı?
================================================================================
[!] UYARI: 25 adet 'record_id' birden fazla farklı başlığa sahip!

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN
5,rec_00033,A Beam-Scannable Photonic THz-ISAC System Base...,"Z. Lyu, Lu Zhang, Hongqi Zhang, Zuomin Yang, H...",2023,2023 Asia Communications and Photonics Confere...,10.1109/acp/poem59049.2023.10368958,https://doi.org/10.1109/ACP/POEM59049.2023.103...,NaN,NaN,NaN
38,rec_00094,A Unified Waveform for Optical Wireless Integr...,"Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao,...",-,NaN,10.1109/acp55869.2022.10088865,-,NaN,NaN,NaN
400,rec_00094,Optical Integrated Sensing and Communication,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu",2023,arXiv.org,10.1109/acp55869.2022.10088865,https://doi.org/10.48550/arXiv.2305.04395,NaN,NaN,NaN
524,rec_00105,RIS-assisted Integrated Sensing and Communicat...,"Xiao Meng, F. Liu, Shih-Jung Lu, S. Chepuri, C...",2022,International Radar Conference,10.1109/radarconf2351548.2023.10149664,https://doi.org/10.1109/RadarConf2351548.2023....,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
606,rec_00678,STARS Enabled Integrated Sensing and Communica...,"Zhao-Jie Wang, Xidong Mu, Yuanwei Liu",2022,IEEE Transactions on Wireless Communications,10.1109/Ucom59132.2023.10257580,https://doi.org/10.1109/TWC.2023.3245297,NaN,NaN,NaN
201,rec_00744,Holographic Beamforming for Integrated Sensing...,"Shuhao Zeng, Haobo Zhang, Boya Di, Hongliang Z...",2025,-,10.1109/jsac.2025.3612921,-,NaN,NaN,NaN
202,rec_00744,Holographic Integrated Sensing and Communication,"Haobo Zhang, Hongliang Zhang, Boya Di, M. D. R...",2022,IEEE Journal on Selected Areas in Communications,10.1109/jsac.2025.3612921,https://doi.org/10.1109/jsac.2022.3155548,NaN,NaN,NaN
478,rec_00754,Reconfigurable Intelligent Surface assisted In...,"Jiahua Wan, Member Ieee Hong Ren, Zhiyuan Yu, ...",-,-,10.1109/icasspw62465.2024.10626004,-,NaN,NaN,NaN
479,rec_00754,Reconfigurable Intelligent Surface Assisted In...,"Jiahua Wan, Hong Ren, Cunhua Pan, Zhiyuan Yu, ...",2024,2024 IEEE International Conference on Acoustic...,10.1109/icasspw62465.2024.10626004,https://doi.org/10.1109/ICASSPW62465.2024.1062...,NaN,NaN,NaN

================================================================================
KONTROL 2: Aynı 'title' için farklı 'record_id' var mı?
================================================================================
[✓] Mükemmel! İçerik mükerrerliği görünmüyor.

================================================================================
KONTROL 3: Hem 'record_id' hem de 'title' aynı olan satırlar var mı?
================================================================================
[!] UYARI: 41 adet satır, hem 'record_id' hem de 'title' bazında tamamen mükerrer.

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
337,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,-,NaN,10.1109/lcomm.2022.3195062,-,NaN,NaN,NaN
336,rec_00021,Joint Waveform and Phase Shift Design for RIS-...,Hongliang Zhang,2022,IEEE Communications Letters,10.1109/lcomm.2022.3195062,https://doi.org/10.1109/LCOMM.2022.3195062,NaN,NaN,NaN
27,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2024,NaN,10.1109/tits.2023.3330172,-,NaN,NaN,NaN
28,rec_00037,A RIS-Based Vehicle DOA Estimation Method With...,"Zhimin Chen, Peng Chen, Ziyu Guo, Yudong Zhang...",2022,IEEE transactions on intelligent transportatio...,10.1109/tits.2023.3330172,https://doi.org/10.1109/TITS.2023.3330172,NaN,NaN,NaN
321,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",2024,IEEE Wireless Communications Letters,10.1109/lwc.2024.3365809,https://doi.org/10.1109/LWC.2024.3365809,NaN,NaN,NaN
322,rec_00054,Joint Resource Allocation and Reflecting Preco...,"Xiaohui Li, Hong Wang, Yunpei Chen, Shuran Sheng",-,NaN,10.1109/lwc.2024.3365809,-,NaN,NaN,NaN
471,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",-,NaN,10.1109/nnice61279.2024.10498998,-,NaN,NaN,NaN
470,rec_00078,Recent advances in integrated sensing and comm...,"Yufeng Zhang, Minglun Zhang",2024,2024 4th International Conference on Neural Ne...,10.1109/nnice61279.2024.10498998,https://doi.org/10.1109/NNICE61279.2024.10498998,NaN,NaN,NaN
446,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, Xihua Zou, Ningyuan Zh...",-,NaN,10.1109/jstqe.2023.3276903,-,NaN,NaN,NaN
445,rec_00086,Photonics-assisted Millimeter-Wave Multiband I...,"Wenlin Bai, Peixuan Li, X. Zou, Ningyuan Zhong...",2023,IEEE Journal of Selected Topics in Quantum Ele...,10.1109/jstqe.2023.3276903,https://doi.org/10.1109/JSTQE.2023.3276903,NaN,NaN,NaN
385,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yua Chen, Jianhe Du, Jianbo Liu, Libiao Jin, X...",-,NaN,10.1109/tvt.2023.3324448,-,NaN,NaN,NaN
386,rec_00098,Nested Tensor-Based Framework for ISAC Assiste...,"Yuan Cheng, Jianhe Du, Jianbo Liu, Libiao Jin,...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3324448,https://doi.org/10.1109/TVT.2023.3324448,NaN,NaN,NaN
297,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",2024,IEEE Wireless Communications Letters,10.1109/lwc.2023.3327360,https://doi.org/10.1109/LWC.2023.3327360,NaN,NaN,NaN
298,rec_00099,Joint Beamforming for RIS-Assisted Integrated ...,"Yue Yang, Hui Gao, Xiaoyu Yang, Ruohan Cao, Yo...",-,NaN,10.1109/lwc.2023.3327360,-,NaN,NaN,NaN
208,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,NaN,10.1109/tvt.2023.3343379,-,NaN,NaN,NaN
209,rec_00100,Hybrid NOMA Assisted Integrated Sensing and Co...,"Wanting Lyu, Yue Xiu, Xinyang Li, Songjie Yang...",2023,IEEE Transactions on Vehicular Technology,10.1109/tvt.2023.3343379,https://doi.org/10.1109/TVT.2023.3343379,NaN,NaN,NaN
580,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, O. Dobre, Geoffrey ...",2023,IEEE Transactions on Wireless Communications,10.1109/twc.2023.3302319,https://doi.org/10.1109/TWC.2023.3302319,NaN,NaN,NaN
579,rec_00104,Simultaneous Beam Training and Target Sensing ...,"Kangjian Chen, Chenhao Qi, Octavia A Dobre, Ge...",2024,NaN,10.1109/twc.2023.3302319,-,NaN,NaN,NaN
637,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zha, Tianqi Mao, Rui Na, Zhaoch...",2025,NaN,10.1109/tvt.2024.3517709,-,NaN,NaN,NaN
638,rec_00106,Transmit Beamforming Design for ISAC With Stac...,"Shunyu Li, Fan Zhang, Tianqi Mao, Rui Na, Zhao...",2024,IEEE Transactions on Vehicular Technology,10.1109/tvt.2024.3517709,https://doi.org/10.1109/TVT.2024.3517709,NaN,NaN,NaN
466,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Wen Chen, Qingqing Wu, Jinhong Yuan, Shanshan ...",-,NaN,10.1109/jiot.2024.3397736,-,NaN,NaN,NaN
465,rec_00108,Rate-Splitting Multiple Access for Transmissiv...,"Ziwei Liu, Wen Chen, Qing-Bin Wu, Jinghong Yua...",2024,IEEE Internet of Things Journal,10.1109/jiot.2024.3397736,https://doi.org/10.1109/JIOT.2024.3397736,NaN,NaN,NaN
187,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, Gabriele...",-,NaN,10.23919/eucap60739.2024.10501539,-,NaN,NaN,NaN
188,rec_00110,Fully Autonomous Reconfigurable Metasurfaces w...,"Hamidreza Taghvaee, Maryam Khodadadi, G. Grado...",2024,European Conference on Antennas and Propagation,10.23919/eucap60739.2024.10501539,https://doi.org/10.23919/EuCAP60739.2024.10501539,NaN,NaN,NaN
312,rec_00111,Joint Localization and Information Transfer fo...,"Z. Shao, Xiaojun Yuan, W. Zhang, M. Di Renzo",2022,Global Communications Conference,10.1109/globecom48099.2022.10001508,https://doi.org/10.1109/GLOBECOM48099.2022.100...,NaN,NaN,NaN
313,rec_00111,Joint Localization and Information Transfer fo...,"Zhichao Shao, Xiaojun Yuan, Wei Zhang, Marco D...",-,NaN,10.1109/globecom48099.2022.10001508,-,NaN,NaN,NaN
164,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",2024,IEEE Military Communications Conference,10.1109/milcom61039.2024.10774028,https://doi.org/10.1109/MILCOM61039.2024.10774028,NaN,NaN,NaN
165,rec_00112,Enhancing Battlefield Awareness: An Aerial RIS...,"Hyunsang Cho, Seonghoon Yoo, Bang Chul Jung, J...",-,NaN,10.1109/milcom61039.2024.10774028,-,NaN,NaN,NaN
83,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R. Sankar, S. Chepuri",2022,European Signal Processing Conference,10.23919/eusipco55093.2022.9909562,https://doi.org/10.48550/arXiv.2203.05902,NaN,NaN,NaN
84,rec_00114,Beamforming in Hybrid RIS assisted Integrated ...,"R S Prasobh Sankar, Sundeep Prabhakar Chepuri",-,NaN,10.23919/eusipco55093.2022.9909562,-,NaN,NaN,NaN
299,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Yongqing Xu, Yong Li, J Andrew Zhang, Marco Di...",2023,NaN,10.1109/TVT.2022.3197448,-,NaN,NaN,NaN
300,rec_00263,Joint Beamforming for RIS-Assisted Integrated ...,"Graduate Student Member Ieee Yongqing Xu, Memb...",2023,IEEE Transactions on Communications,10.1109/TVT.2022.3197448,https://doi.org/10.1109/TCOMM.2023.3344143,NaN,NaN,NaN
408,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2023,IEEE Internet of Things Magazine,10.48550/arXiv.2305.04395,https://doi.org/10.1109/IOTM.001.2300196,NaN,NaN,NaN
407,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
406,rec_00408,Optical Integrated Sensing and Communication w...,"Runxin Zhang, Yulin Shao, Menghan Li, Lu Lu, Y...",2024,2024 IEEE International Conference on Communic...,10.48550/arXiv.2305.04395,https://doi.org/10.1109/ICCWorkshops59551.2024...,NaN,NaN,NaN
404,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bin Zhu",2024,IEEE Transactions on Wireless Communications,10.48550/arXiv.2305.04395,https://doi.org/10.1109/TWC.2024.3484569,NaN,NaN,NaN
403,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
402,rec_00408,Optical Integrated Sensing and Communication S...,"Haibo Wang, Zaichen Zhang, Yingmeng Ge, Bingch...",-,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
409,rec_00408,Optical Integrated Sensing and Communication: ...,"Yunfeng Wen, Fang Yang, Jian Song, Zhu Han",2024,NaN,10.48550/arXiv.2305.04395,-,NaN,NaN,NaN
389,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN
390,NaN,No title found,-,-,NaN,-,-,NaN,NaN,NaN

In [66]:
# Başlamadan önce mevcut durumu görelim
print(f"Düzeltme işleminden önceki toplam kayıt sayısı: {len(included)}")

# Adım 1: Hem 'record_id' hem de 'title' bazında tam mükerrer olanları sil
# 'subset' parametresi hangi sütunlara bakılacağını belirtir.
# 'keep='first'' varsayılan davranıştır ama açıkça belirtmek iyidir.
# Değişiklikleri yeni bir DataFrame'e atamak, orijinal veriyi korumak için iyi bir pratiktir.
included_step1 = included.drop_duplicates(subset=['record_id', 'title'], keep='first')

# Sonucu kontrol edelim
print(f"Tam mükerrer satırlar temizlendikten sonraki kayıt sayısı: {len(included_step1)}")
silinen_satir_sayisi = len(included) - len(included_step1)

if silinen_satir_sayisi > 0:
    print(f"Başarılı! {silinen_satir_sayisi} adet tam mükerrer satır temizlendi.")
else:
    print("Bu adımda silinecek tam mükerrer satır bulunamadı.")

# Gelecek adımlarda bu temizlenmiş DataFrame'i kullanacağız.
# İstersen orijinal 'included' DataFrame'ini güncelleyebilirsin:
# included = included.drop_duplicates(subset=['record_id', 'title'], keep='first')

Düzeltme işleminden önceki toplam kayıt sayısı: 660
Tam mükerrer satırlar temizlendikten sonraki kayıt sayısı: 639
Başarılı! 21 adet tam mükerrer satır temizlendi.

In [67]:
# Önce çakışan ID'leri tekrar tespit edelim (eğer varsa)
id_to_title_counts = included_step1.groupby('record_id')['title'].nunique()
conflicting_ids = id_to_title_counts[id_to_title_counts > 1].index.tolist()

if conflicting_ids:
    print(f"{len(conflicting_ids)} adet çakışan 'record_id' üzerinde işlem yapılacak.")
    
    # Strateji: Her çakışan 'record_id' için sadece İLK karşılaşılan satırı tut.
    # Bunu, sadece 'record_id' sütununa göre 'drop_duplicates' uygulayarak yapabiliriz.
    # ÖNEMLİ: Bu işlemi TÜM DataFrame'e uygularsak, henüz bakmadığımız
    # içerik mükerrerlerini de yanlışlıkla silebiliriz. Bu yüzden dikkatli olmalıyız.
    # Ancak bu aşamada bu sorunu çözmek için en temiz yoldur.
    
    print(f"Çakışma çözme işleminden önceki kayıt sayısı: {len(included_step1)}")
    
    # 'record_id' bazında tekilleştirme yapıyoruz. Bu, her ID'nin sadece bir kez yer almasını sağlar.
    included_step2 = included_step1.drop_duplicates(subset=['record_id'], keep='first')
    
    print(f"Çakışan 'record_id'ler çözüldükten sonraki kayıt sayısı: {len(included_step2)}")
    
    silinen_satir_sayisi = len(included_step1) - len(included_step2)
    print(f"Başarılı! Çakışan kayıtlardan {silinen_satir_sayisi} tanesi temizlendi.")

else:
    print("Çakışan 'record_id' bulunmuyor. Bu adım atlanabilir.")
    included_step2 = included_step1.copy() # Değişiklik yoksa kopyasını oluştur.

25 adet çakışan 'record_id' üzerinde işlem yapılacak.
Çakışma çözme işleminden önceki kayıt sayısı: 639
Çakışan 'record_id'ler çözüldükten sonraki kayıt sayısı: 607
Başarılı! Çakışan kayıtlardan 32 tanesi temizlendi.

In [68]:
# Şimdi 'title' sütununa göre tekilleştirme yapalım.
print(f"İçerik tekilleştirme işleminden önceki kayıt sayısı: {len(included_step2)}")

# 'title' bazında mükerrer olanları sil.
included_step3 = included_step2.drop_duplicates(subset=['title'], keep='first')

print(f"İçerik mükerrerleri temizlendikten sonraki nihai kayıt sayısı: {len(included_step3)}")
silinen_satir_sayisi = len(included_step2) - len(included_step3)

if silinen_satir_sayisi > 0:
    print(f"Başarılı! {silinen_satir_sayisi} adet içerik mükerreri temizlendi.")
else:
    print("Bu adımda silinecek içerik mükerreri bulunamadı.")

# Nihai temizlenmiş DataFrame'imiz hazır!
final_included = included_step3.copy()
print("\\nTüm temizlik adımları tamamlandı!")

İçerik tekilleştirme işleminden önceki kayıt sayısı: 607
İçerik mükerrerleri temizlendikten sonraki nihai kayıt sayısı: 607
Bu adımda silinecek içerik mükerreri bulunamadı.
\nTüm temizlik adımları tamamlandı!

In [69]:
final_included

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
0,rec_00702,1- bit Reconfigurable Intelligent Surface for ...,"Deepak, Akhila Gouda, Saptarshi Ghosh",2025,2025 Third International Conference on Microwa...,10.1109/MAC64480.2025.11140492,https://doi.org/10.1109/MAC64480.2025.11140492,NaN,NaN,NaN
1,rec_00158,1000-Channel Integrated Optical Phased Array w...,"Yong Liu, Xiansong Meng",-,NaN,arXiv:2508.19977,-,NaN,NaN,NaN
2,rec_00585,2-Bit RIS Prototyping Enhancing Rapid-Response...,"Yufei Zhao, Yuan Feng, Afkar Mohamed Ismail, Z...",2024,IEEE Open Journal of the Communications Society,10.1109/OJCOMS.2024.3439558,https://doi.org/10.1109/OJCOMS.2024.3439558,NaN,NaN,NaN
3,rec_00040,6G INTEGRATED SENSING AND COMMUNICATION -SENSI...,"Zhi Zhou, Xianjin Li, Jia He, Xiaoyan Bi, Yan ...",-,NaN,10.1109/icassp49357.2023.10096544,-,NaN,NaN,NaN
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
655,rec_00661,"Wideband, Polarization-Agile Reconfigurable In...","Sanghamitro Das, Satish K. Sharma",2024,United States National Committee of URSI Natio...,10.23919/USNC-URSINRSM60317.2024.10464458,https://doi.org/10.23919/USNC-URSINRSM60317.20...,NaN,NaN,NaN
656,rec_00134,Wireless microwave-to-optical conversion via p...,"Xin Ge Zhang, Ya Lun Sun, Bingcheng Zhu, Han W...",-,NaN,10.1038/s41467-025-55940-9,-,NaN,NaN,NaN
657,rec_00725,XL-RIS Enabled Near-Field Integrated Sensing a...,"Ping Sun, Yongsheng Ma, Qianyu Yang, Haibo Dai...",2025,IEEE Internet of Things Journal,10.1109/JIOT.2025.3567568,https://doi.org/10.1109/JIOT.2025.3567568,NaN,NaN,NaN
658,rec_00734,感知一体化系统 Reconfigurable Intelligent Surface-Ass...,"杨晓宇 Yang, Xiaoyu ，尉志青, Wei, Zhiqing ， 孟春伟, Men...",-,-,10.1145/3556562.3558576,-,NaN,NaN,NaN
659,rec_00277,智能超表面 辅助通信感知一体化 RIS-Assisted Integrated Sensin...,"夏方昊 Xia, Fanghao ，王新奕, Wang, Zheng Zhong",2022,-,https://api.semanticscholar.org/CorpusID:26126...,-,NaN,NaN,NaN

In [70]:
import pandas as pd

print("--- `final_included` DataFrame'i için Son Doğrulama Başlatıldı ---")

# Varsayım: 'final_included' adında bir DataFrame'in mevcut.
# Eğer yoksa, aşağıdaki satırı yorumdan çıkarıp test için oluşturabilirsiniz.
# final_included = pd.DataFrame(...) 

# --- KONTROL 1: AYNI ID, FARKLI BAŞLIK (EN KRİTİK HATA) ---
print("\n" + "="*80)
print("KONTROL 1: Aynı 'record_id' için farklı 'title' var mı?")
print("="*80)
id_to_title_counts = final_included.groupby('record_id')['title'].nunique()
conflicting_ids = id_to_title_counts[id_to_title_counts > 1].index.tolist()

if conflicting_ids:
    print(f"[!] HATA: Temizliğe rağmen {len(conflicting_ids)} adet 'record_id' hala birden fazla başlığa sahip!")
    conflicting_entries = final_included[final_included['record_id'].isin(conflicting_ids)].sort_values('record_id')
    display(conflicting_entries)
else:
    print("[✓] Harika! Her 'record_id' yalnızca tek bir benzersiz başlığa sahip.")

# --- KONTROL 2: FARKLI ID, AYNI BAŞLIK (İÇERİK MÜKERRERLİĞİ) ---
print("\n" + "="*80)
print("KONTROL 2: Aynı 'title' için farklı 'record_id' var mı?")
print("="*80)
title_to_id_counts = final_included.groupby('title')['record_id'].nunique()
duplicate_titles = title_to_id_counts[title_to_id_counts > 1].index.tolist()

if duplicate_titles:
    print(f"[!] HATA: Temizliğe rağmen {len(duplicate_titles)} adet başlık hala birden fazla 'record_id' ile eşleşiyor!")
    duplicate_content_entries = final_included[final_included['title'].isin(duplicate_titles)].sort_values('title')
    display(duplicate_content_entries)
else:
    print("[✓] Mükemmel! İçerik mükerrerliği tamamen temizlenmiş.")

# --- KONTROL 3: AYNI ID, AYNI BAŞLIK (TAM MÜKERRERLİK) ---
print("\n" + "="*80)
print("KONTROL 3: Hem 'record_id' hem de 'title' aynı olan satırlar var mı?")
print("="*80)
full_duplicates = final_included[final_included.duplicated(subset=['record_id', 'title'], keep=False)]

if not full_duplicates.empty:
    print(f"[!] HATA: Temizliğe rağmen {len(full_duplicates)} adet satır hala tam mükerrer!")
    display(full_duplicates.sort_values('record_id'))
else:
    print("[✓] Çok iyi! 'record_id' ve 'title' bazında tam mükerrer satır yok.")

print("\n--- Doğrulama Tamamlandı ---")

--- `final_included` DataFrame'i için Son Doğrulama Başlatıldı ---

================================================================================
KONTROL 1: Aynı 'record_id' için farklı 'title' var mı?
================================================================================
[✓] Harika! Her 'record_id' yalnızca tek bir benzersiz başlığa sahip.

================================================================================
KONTROL 2: Aynı 'title' için farklı 'record_id' var mı?
================================================================================
[✓] Mükemmel! İçerik mükerrerliği tamamen temizlenmiş.

================================================================================
KONTROL 3: Hem 'record_id' hem de 'title' aynı olan satırlar var mı?
================================================================================
[✓] Çok iyi! 'record_id' ve 'title' bazında tam mükerrer satır yok.

--- Doğrulama Tamamlandı ---

In [79]:
import os
import pandas as pd

# 1. Kayıt edilecek dizini ve dosya adını tanımla
output_directory = 'data'
output_filename = 'included_studies.csv'
output_filepath = os.path.join(output_directory, output_filename)

# 2. 'data' klasörünün var olup olmadığını kontrol et, yoksa oluştur
# os.makedirs, iç içe klasörler oluşturabilir ve exist_ok=True parametresi
# klasör zaten varsa hata vermesini engeller. Bu, kodu tekrar tekrar
# çalıştırmak için çok kullanışlıdır.
os.makedirs(output_directory, exist_ok=True)

print(f"'{output_directory}' klasörü kontrol edildi ve hazır.")

# 3. DataFrame'i CSV olarak kaydet
# index=False parametresi, DataFrame'in index'ini (0, 1, 2, ...)
# CSV dosyasında ayrı bir sütun olarak kaydetmeyi önler. Bu çok önemlidir!
# encoding='utf-8-sig' parametresi, Türkçe karakterlerin Excel gibi
# programlarda doğru görüntülenmesini sağlar.
final_included.to_csv(output_filepath, index=False, encoding='utf-8-sig')

print(f"Başarılı! Temizlenmiş veri seti {len(final_included)} satır ile şuraya kaydedildi:")
print(f"--> {output_filepath}")

# İsteğe bağlı: Kaydedilen dosyayı okuyarak hızlı bir kontrol yapabiliriz
print("\nDosyanın doğru kaydedildiğini kontrol etmek için ilk 5 satır okunuyor...")
try:
    saved_df = pd.read_csv(output_filepath)
    display(saved_df.head())
    print("\nKontrol başarılı. Dosya düzgün bir şekilde okunabiliyor.")
except FileNotFoundError:
    print(f"[HATA] Dosya '{output_filepath}' konumunda bulunamadı. Kayıt işlemi başarısız olmuş olabilir.")

'data' klasörü kontrol edildi ve hazır.
Başarılı! Temizlenmiş veri seti 607 satır ile şuraya kaydedildi:
--> data/included_studies.csv

Dosyanın doğru kaydedildiğini kontrol etmek için ilk 5 satır okunuyor...

,record_id,title,authors,year,venue,doi,url,citation,pub_type,peer_reviewed
0,rec_00702,1- bit Reconfigurable Intelligent Surface for ...,"Deepak, Akhila Gouda, Saptarshi Ghosh",2025,2025 Third International Conference on Microwa...,10.1109/MAC64480.2025.11140492,https://doi.org/10.1109/MAC64480.2025.11140492,NaN,NaN,NaN
1,rec_00158,1000-Channel Integrated Optical Phased Array w...,"Yong Liu, Xiansong Meng",-,NaN,arXiv:2508.19977,-,NaN,NaN,NaN
2,rec_00585,2-Bit RIS Prototyping Enhancing Rapid-Response...,"Yufei Zhao, Yuan Feng, Afkar Mohamed Ismail, Z...",2024,IEEE Open Journal of the Communications Society,10.1109/OJCOMS.2024.3439558,https://doi.org/10.1109/OJCOMS.2024.3439558,NaN,NaN,NaN
3,rec_00040,6G INTEGRATED SENSING AND COMMUNICATION -SENSI...,"Zhi Zhou, Xianjin Li, Jia He, Xiaoyan Bi, Yan ...",-,NaN,10.1109/icassp49357.2023.10096544,-,NaN,NaN,NaN
4,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",-,NaN,10.1109/acp/poem59049.2023.10368958,-,NaN,NaN,NaN

Kontrol başarılı. Dosya düzgün bir şekilde okunabiliyor.

In [76]:
%%ai

UsageError: %%ai is a cell magic, but the cell body is empty. Did you mean the line magic %ai (single %)?

In [77]:
import pandas as pd
import os

# --- Adım 1: Dosya Yollarını Tanımlama ---
elicit_file_path = os.path.join('Downloads', 'elicit_with_record_ids-2.csv')
studies_file_path = os.path.join('data', 'included_studies.csv')

In [82]:
import pandas as pd
import os

# --- Adım 1: Dosya Yollarını Tanımlama ---
# BURAYI KENDİ BİLGİSAYARINIZDAKİ TAM YOL İLE DEĞİŞTİRİN!
# ÖRNEK: elicit_file_path = "C:\\Users\\KullanıcıAdı\\Downloads\\elicit_with_record_ids-2.csv"
elicit_file_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'elicit_with_record_ids-2.csv')
studies_file_path = os.path.join('data', 'included_studies.csv')

print("İşlem başlıyor...")
print(f"Ana veri dosyası: '{elicit_file_path}'")

try:
    # --- Adım 2: Ana CSV Dosyasını DataFrame'e Yükleme ---
    df_elicit = pd.read_csv(elicit_file_path)
    print(f"\n✅ '{elicit_file_path}' dosyası başarıyla yüklendi.")
    print(f"Başlangıçtaki toplam satır sayısı: {df_elicit.shape[0]}")

    # --- Adım 3: Veri Tutarsızlıklarını Tespit Etme ve Ayırma ---
    print("\n" + "="*50)
    print("YENİ ADIM: Tutarsız Verileri Tespit Et ve Ayrı Bir DataFrame'e Topla")
    print("="*50)

    # KONTROL 1: Farklı record_id, Aynı title
    #----------------------------------------------------
    print("\n>>> KONTROL 1: Aynı başlığa sahip FARKLI record_id'ler aranıyor...")
    title_id_counts = df_elicit.groupby('Title')['record_id'].nunique()
    conflicting_titles = title_id_counts[title_id_counts > 1].index
    
    # KONTROL 2: Aynı record_id, Farklı title
    #----------------------------------------------------
    print(">>> KONTROL 2: Aynı record_id'ye sahip FARKLI başlıklar aranıyor...")
    id_title_counts = df_elicit.groupby('record_id')['Title'].nunique()
    conflicting_ids = id_title_counts[id_title_counts > 1].index
    
    # Tespit edilen tüm tutarsız satırları filtreleyerek alalım
    inconsistent_type1_df = df_elicit[df_elicit['Title'].isin(conflicting_titles)]
    inconsistent_type2_df = df_elicit[df_elicit['record_id'].isin(conflicting_ids)]

    if not inconsistent_type1_df.empty or not inconsistent_type2_df.empty:
        # İki türdeki tutarsız DataFrame'leri birleştirelim
        df_all_inconsistent = pd.concat([inconsistent_type1_df, inconsistent_type2_df]).drop_duplicates().reset_index(drop=True)
        
        print(f"\n🚨 TOPLAM {df_all_inconsistent.shape[0]} ADET TUTARSIZ SATIR BULUNDU.")
        print("Bu satırlar ayrı bir DataFrame'de toplanıyor ve ana veriden çıkarılacak.")
        print("\nİşte incelenmesi gereken tutarsız verilerden ilk 5 örnek:")
        display(df_all_inconsistent.head())

        # YENİ TEMİZ DATAFRAME: Tutarsız satırların indekslerini kullanarak ana DataFrame'den düşelim
        clean_indices = df_elicit.index.difference(df_all_inconsistent.index)
        df_elicit_clean = df_elicit.loc[clean_indices]
        
        print(f"\nOrijinal satır sayısı: {df_elicit.shape[0]}")
        print(f"Ayrılan tutarsız satır sayısı: {df_all_inconsistent.shape[0]}")
        print(f"Analize devam edilecek TEMİZ satır sayısı: {df_elicit_clean.shape[0]}")
    else:
        print("\n✅ GÜZEL HABER: Veri setinde herhangi bir tutarsızlık bulunamadı.")
        df_all_inconsistent = pd.DataFrame()
        df_elicit_clean = df_elicit.copy()

    # --- Adım 4: Filtreleme İçin Kullanılacak DataFrame'i Yükleme ---
    print("\n" + "="*50)
    print("Filtreleme Aşamasına Geçiliyor...")
    print("="*50)
    
    df_studies = pd.read_csv(studies_file_path)
    print(f"\n✅ '{studies_file_path}' dosyası başarıyla yüklendi.")
    print(f"Filtreleme için {df_studies.shape[0]} adet benzersiz ID bulundu.")

    # --- Adım 5: Saklanacak 'record_id'leri Bir Kümeye (Set) Alma ---
    record_ids_to_keep = set(df_studies['record_id'].unique())
    
    # --- Adım 6: TEMİZ DataFrame'i Filtreleme ---
    df_final_filtered = df_elicit_clean[df_elicit_clean['record_id'].isin(record_ids_to_keep)]
    
    print(f"\n✅ ID'lere göre filtreleme işlemi TEMİZ VERİ üzerinde tamamlandı.")
    print(f"Son filtreleme sonrası kalan satır sayısı: {df_final_filtered.shape[0]}")

    # --- Adım 7: Sonuçları Gözden Geçirme ---
    print("\nNihai olarak filtrelenmiş ve temizlenmiş verinin ilk 5 satırı (`df_final_filtered`):")
    display(df_final_filtered.head())
    
except FileNotFoundError as e:
    print(f"\n❌ HATA: Dosya bulunamadı! Lütfen dosya yollarını kontrol edin.")
    print(f"Hata detayı: {e}")
except KeyError as e:
    print(f"\n❌ HATA: Sütun bulunamadı! Dosyalarda 'record_id' veya 'title' adında bir sütun olduğundan emin olun.")
    print(f"Hata detayı: {e}")
except Exception as e:
    print(f"\nBeklenmedik bir hata oluştu: {e}")

İşlem başlıyor...
Ana veri dosyası: '/Users/bastt/Downloads/elicit_with_record_ids-2.csv'

✅ '/Users/bastt/Downloads/elicit_with_record_ids-2.csv' dosyası başarıyla yüklendi.
Başlangıçtaki toplam satır sayısı: 660

==================================================
YENİ ADIM: Tutarsız Verileri Tespit Et ve Ayrı Bir DataFrame'e Topla
==================================================

>>> KONTROL 1: Aynı başlığa sahip FARKLI record_id'ler aranıyor...
>>> KONTROL 2: Aynı record_id'ye sahip FARKLI başlıklar aranıyor...

🚨 TOPLAM 62 ADET TUTARSIZ SATIR BULUNDU.
Bu satırlar ayrı bir DataFrame'de toplanıyor ve ana veriden çıkarılacak.

İşte incelenmesi gereken tutarsız verilerden ilk 5 örnek:

,record_id,Title,Authors,DOI,DOI link,Venue,Citation count,Year,Filename,Technology Integration,...,"Reasoning for ""Performance Trade-offs""","Supporting quotes for ""Experimental Validation""","Supporting tables for ""Experimental Validation""","Reasoning for ""Experimental Validation""","Supporting quotes for ""Key Findings""","Supporting tables for ""Key Findings""","Reasoning for ""Key Findings""","Supporting quotes for ""Challenges/Limitations""","Supporting tables for ""Challenges/Limitations""","Reasoning for ""Challenges/Limitations"""
0,rec_00033,A Beam-scannable photonic THz-ISAC system base...,"Zhidong Lyu, Lu Zhang, Hongqi Zhang, Zuomin Ya...",10.1109/acp/poem59049.2023.10368958,-,NaN,-,-,A_Beam-Scannable_Photonic_THz-ISAC_System_Base...,- Architecture_Type: Hybrid\n- Placement: Co-l...,...,- The paper discusses the performance of a bea...,"- ""In this paper, we propose and experimenta...",NaN,"- The paper mentions an ""experimental demonstr...","- ""20 Gbps data rate and 1.5 cm resolution a...",NaN,- The paper demonstrates a beam-scannable phot...,"- ""there lack sufficient discussions on a sy...",NaN,- The paper discusses the challenges related t...
1,rec_00033,A Beam-Scannable Photonic THz-ISAC System Base...,"Z. Lyu, Lu Zhang, Hongqi Zhang, Zuomin Yang, H...",10.1109/acp/poem59049.2023.10368958,https://doi.org/10.1109/ACP/POEM59049.2023.103...,2023 Asia Communications and Photonics Confere...,1,2023,-,- Architecture_Type: Hybrid\n- Placement: Co-l...,...,- The paper discusses the performance of a bea...,"- ""We propose in this paper a beam-scannable...",NaN,"- The paper describes an ""experimental demonst...","- ""20 Gbps data rate and 1.5 cm resolution a...",NaN,- The paper demonstrates a beam-scannable phot...,"- ""there lack sufficient discussions on a sy...",NaN,- The paper discusses the challenges related t...
2,rec_00372,A Multi-Functional Reconfigurable Intelligent ...,"M. B. Sahin, O. Civi",10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1109/AP-S/INC-USNC-URSI5205...,2024 IEEE International Symposium on Antennas ...,0,2024,-,Architecture_Type: Hybrid\nPlacement: Co-locat...,...,- The paper discusses the design of a Reconfig...,"- ""7x7 RIS is formed and some simulations fo...",NaN,- The paper primarily discusses simulations pe...,"- ""The square unit cell of size $\lambda/2$ ...",NaN,- The paper presents a novel Reconfigurable In...,"- ""To reduce the complexity of the implement...",NaN,- The paper discusses the challenge of reducin...
3,rec_00372,A reconfigurable intelligent surface with inte...,"Idban Alamzadeh, G. C. Alexandropoulos, Nir Sh...",10.1109/AP-S/INC-USNC-URSI52054.2024.10686983,https://doi.org/10.1038/s41598-021-99722-x,Scientific Reports,117,2021,-,- Architecture_Type: Hybrid\n- Placement: Co-l...,...,- The paper discusses the need to balance the ...,"- ""In this paper, we proposed a reconfigurab...",NaN,- The paper discusses the design and simulatio...,"- ""By modifying the tunable meta-atoms const...",NaN,- The paper introduces a reconfigurable intell...,"- ""A key challenge in implementing such RISs...",NaN,- The paper identifies several challenges and ...
4,rec_00094,A Unified Waveform for Optical Wireless Integr...,"Minghua Cao, Ying Wang, Yue Zhang, Daqing Gao,...",10.1109/acp55869.2022.10088865,-,NaN,-,-,A_Unified_Waveform_for_Optical_Wireless_Integr...,- Architecture_Type: Hybrid\n- Placement: Unkn...,...,- The paper discusses the design of a unified ...,"- ""the proposed ISAC-OW system is simulated ...","- ""(Page 4, Table 1) | References | Method...",- The paper mentions that the proposed ISAC-OW...,"- ""The results show that our proposal can no...","- ""(Page 4, Table 1) | References | Method...",- The paper proposes a unified waveform for op...,"- ""the practical atmospheric channel has the...",NaN,- The paper identifies the main challenge as d...

Orijinal satır sayısı: 660
Ayrılan tutarsız satır sayısı: 62
Analize devam edilecek TEMİZ satır sayısı: 598

==================================================
Filtreleme Aşamasına Geçiliyor...
==================================================

✅ 'data/included_studies.csv' dosyası başarıyla yüklendi.
Filtreleme için 607 adet benzersiz ID bulundu.

✅ ID'lere göre filtreleme işlemi TEMİZ VERİ üzerinde tamamlandı.
Son filtreleme sonrası kalan satır sayısı: 598

Nihai olarak filtrelenmiş ve temizlenmiş verinin ilk 5 satırı (`df_final_filtered`):

,record_id,Title,Authors,DOI,DOI link,Venue,Citation count,Year,Filename,Technology Integration,...,"Reasoning for ""Performance Trade-offs""","Supporting quotes for ""Experimental Validation""","Supporting tables for ""Experimental Validation""","Reasoning for ""Experimental Validation""","Supporting quotes for ""Key Findings""","Supporting tables for ""Key Findings""","Reasoning for ""Key Findings""","Supporting quotes for ""Challenges/Limitations""","Supporting tables for ""Challenges/Limitations""","Reasoning for ""Challenges/Limitations"""
62,rec_00529,Application of Re-Configurable Intelligence Su...,"Hu He, Guoxin Hao, Bin Wen, Hao Jiang",10.1109/CISCE62493.2024.10653396,https://doi.org/10.1109/CISCE62493.2024.10653396,2024 6th International Conference on Communica...,1,2024,-,Architecture_Type: RIS-only\nPlacement: Distri...,...,- The paper discusses the design and layout of...,"- ""simulation experiments are conducted in f...",NaN,"- The paper mentions ""simulation experiments"" ...","- ""The structure design and array electronic...",NaN,- The paper discusses the application of Re-co...,"- ""However, with the development of modern i...",NaN,- The paper discusses several challenges relat...
63,rec_00266,Applications of Reconfigurable Intelligent Sur...,"刘让 Liu, Rang ，罗泓昊, Luo, Honghao ，李明, Li",10.1016/b978-0-44-322143-9.00010-2,-,-,0,2022,-,- Architecture_Type: Hybrid\n- Placement: UAV/...,...,"- The abstract discusses the feasibility, adva...","- ""It is believed that artificial intelligen...",NaN,- The abstract discusses the review of functio...,"- ""the feasibility, advancements, and prospe...",NaN,- The abstract discusses the feasibility and a...,"- ""the challenges and opportunities of deplo...",NaN,"- The abstract mentions ""the challenges and op..."
64,rec_00189,Artificial intelligence in meta-optics,"Mu Ku Chen, Xiaoyuan Liu, Yanni Sun, Din Ping ...",10.1021/acs.chemrev.2c00012,https://doi.org/10.1021/acs.chemrev.2c00012,Chemical Reviews,-,2022,NaN,Architecture_Type: Hybrid\nPlacement: Unknown\...,...,- The paper discusses several performance trad...,"- ""Li et al. developed an intelligent imager...","- ""(Page 51, Table 1) | type | traini...",- The paper discusses several experimental val...,"- ""the proposed DNN achieved an accuracy of ...",NaN,- The paper discusses the integration of AI wi...,"- ""Despite the research enthusiasm in this a...",NaN,- The paper discusses several challenges and l...
65,rec_00173,Assessment of adaptive optics-corrected optica...,"Emile Klotz, Sidonie Lefebvre, Nicolas Vedrenn...",10.1002/sat.1497,-,NaN,-,-,FSO_014.pdf,Architecture_Type: Hybrid\nPlacement: Distribu...,...,- The paper discusses the use of adaptive opti...,"- ""Concerning the third hypothesis, on the i...",NaN,- The paper mentions that experimental validat...,"- ""Taking as input only four integrated para...","- ""(Page 7, Table 1) | Relative error | 0.00...",- The paper discusses the use of a Gaussian pr...,"- ""The results presented in this study rely ...",NaN,- The paper discusses several limitations of t...
66,rec_00215,Avalanche photodiodes with dual multiplication...,"Zohauddin Ahmad, Sheng-I Kuo, You-Chia Chang, ...",10.1109/JSTQE.2021.3062637,https://doi.org/10.1109/JSTQE.2021.3062637,IEEE Journal of Selected Topics in Quantum Ele...,-,2021,NaN,Architecture_Type: OPA-only\nPlacement: Co-loc...,...,- The paper discusses the design of an avalanc...,"- ""As compared to the commercially available...",NaN,- The paper describes the development and test...,"- ""Such a cascade avalanche process leads to...",NaN,- The paper introduces a novel avalanche photo...,"- ""In order to compensate for such on-chip i...",NaN,- The paper discusses several challenges relat...

In [83]:
# --- Adım 4: Filtreleme İçin Kullanılacak DataFrame'i Yükleme ---
print("\n" + "="*50)
print("Filtreleme Aşamasına Geçiliyor...")
print("="*50)
 
df_studies = pd.read_csv(studies_file_path)
print(f"\n✅ '{studies_file_path}' dosyası başarıyla yüklendi.")
print(f"Filtreleme için {df_studies.shape[0]} adet benzersiz ID bulundu.")

# --- Adım 5: Saklanacak 'record_id'leri Bir Kümeye (Set) Alma ---
record_ids_to_keep = set(df_studies['record_id'].unique())
 
# --- Adım 6: TEMİZ DataFrame'i Filtreleme ---
df_final_filtered = df_elicit_clean[df_elicit_clean['record_id'].isin(record_ids_to_keep)]

==================================================
Filtreleme Aşamasına Geçiliyor...
==================================================

✅ 'data/included_studies.csv' dosyası başarıyla yüklendi.
Filtreleme için 607 adet benzersiz ID bulundu.

In [84]:
# --- Nihai veriyi kaydetme ---
final_output_path = 'data/final_filtered_data.csv'
df_final_filtered.to_csv(final_output_path, index=False, encoding='utf-8-sig')

print(f"\n✅ Nihai temizlenmiş ve filtrelenmiş veri başarıyla kaydedildi: '{final_output_path}'")
print(f"Toplam {df_final_filtered.shape[0]} satır.")

✅ Nihai temizlenmiş ve filtrelenmiş veri başarıyla kaydedildi: 'data/final_filtered_data.csv'
Toplam 598 satır.

In [87]:
import pandas as pd
import os

# Veri setinizin dosya yolunu tanımlayın
file_path = "data/final_filtered_data.csv"

# Dosyanın var olup olmadığını kontrol edin
if os.path.exists(file_path):
    # Eğer dosya varsa, DataFrame'e yükleyin
    df = pd.read_csv(file_path)
    
    # Sütun adlarını listeleyin
    print("Veri setindeki sütunlar:")
    for column in df.columns:
        print(f"- {column}")
        
    print(f"\nToplam {len(df.columns)} adet sütun bulunmaktadır.")
else:
    print(f"Hata: Belirtilen dosya yolu bulunamadı: {file_path}")
    print("Lütfen dosya yolunun doğru olduğundan ve dosyanın mevcut olduğundan emin olun.")

Veri setindeki sütunlar:
- record_id
- Title
- Authors
- DOI
- DOI link
- Venue
- Citation count
- Year
- Filename
- Technology Integration
- System Specifications
- ISAC Method
- Communication Performance
- Sensing Performance
- Performance Trade-offs
- Experimental Validation
- Key Findings
- Challenges/Limitations
- Supporting quotes for "Technology Integration"
- Supporting tables for "Technology Integration"
- Reasoning for "Technology Integration"
- Supporting quotes for "System Specifications"
- Supporting tables for "System Specifications"
- Reasoning for "System Specifications"
- Supporting quotes for "ISAC Method"
- Supporting tables for "ISAC Method"
- Reasoning for "ISAC Method"
- Supporting quotes for "Communication Performance"
- Supporting tables for "Communication Performance"
- Reasoning for "Communication Performance"
- Supporting quotes for "Sensing Performance"
- Supporting tables for "Sensing Performance"
- Reasoning for "Sensing Performance"
- Supporting quotes for "Performance Trade-offs"
- Supporting tables for "Performance Trade-offs"
- Reasoning for "Performance Trade-offs"
- Supporting quotes for "Experimental Validation"
- Supporting tables for "Experimental Validation"
- Reasoning for "Experimental Validation"
- Supporting quotes for "Key Findings"
- Supporting tables for "Key Findings"
- Reasoning for "Key Findings"
- Supporting quotes for "Challenges/Limitations"
- Supporting tables for "Challenges/Limitations"
- Reasoning for "Challenges/Limitations"

Toplam 45 adet sütun bulunmaktadır.

In [86]:
ls

CITATION.cff                   NotebookJup.ipynb
config/                        protocol/
CONTRIBUTING.md                README.bak.20250926132957
data/                          README.bak.20250926133111
docs/                          README.md
duplicate_titles_analysis.csv  requirements.txt
file_inventory.csv             results/
LICENSE                        scripts/
manuscript/                    supplementary_material.md
memory-bank/                   templates/

In [1]:
import pandas as pd
import os

# --- Adım 1: Dosya Yollarını ve Veri Setini Tanımlama ---
# Veri setinizin dosya yolu
dataframe_file_path = "/data/final_filtered_data.csv"

# Arama yapılacak ana klasörün yolu
search_directory = "OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora"

# --- Adım 2: Veri Setini Yükle ve Filtrele ---
try:
    # DataFrame'i yükle
    df = pd.read_csv(dataframe_file_path)

    # '-' ve boş değerler hariç Filename sütunundaki benzersiz dosya isimlerini al
    # Boş string ('') ve NaN (eksik veri) değerlerini de kontrol ediyoruz
    valid_filenames = df[df['Filename'].notna() & (df['Filename'] != '-') & (df['Filename'] != '')]['Filename'].unique()
    
    print(f"Toplam {len(valid_filenames)} adet dosya adı aranacak.\n")
    
except FileNotFoundError:
    print(f"Hata: Veri seti '{dataframe_file_path}' konumunda bulunamadı. Lütfen dosya yolunu kontrol edin.")
    exit()

# --- Adım 3: Belirtilen Klasörde Dosya Arama ---
found_files = []

# os.walk() fonksiyonu ile ana dizini ve tüm alt dizinlerini dolaş
print(f"'{search_directory}' klasöründe dosya araması başlatılıyor...")
for root, dirs, files in os.walk(search_directory):
    for file in files:
        if file in valid_filenames:
            # Eğer dosya adı aranacaklar listesinde varsa, tam yolunu al
            full_path = os.path.join(root, file)
            found_files.append({'filename': file, 'full_path': full_path})
            print(f"  Bulundu: {full_path}")

# --- Adım 4: Bulunan Dosyaları DataFrame'e Dönüştürme ve Eşleştirme ---
if not found_files:
    print("\nBelirtilen dosya adlarından hiçbiri bulunamadı.")
else:
    found_df = pd.DataFrame(found_files)
    
    # Ana DataFrame ile bulunan dosyaları içeren DataFrame'i birleştir
    # 'Filename' sütununu referans alarak birleştirme yapıyoruz
    merged_df = pd.merge(df, found_df, on='Filename', how='inner')
    
    # Yalnızca gerekli sütunları (record_id, Filename, full_path) seç
    final_df = merged_df[['record_id', 'Filename', 'full_path']]
    
    print(f"\n✅ Toplam {len(final_df)} adet kayıt başarıyla eşleştirildi.")

    # --- Adım 5: Sonuçları CSV Olarak Kaydetme ---
    output_filename = 'matched_files_with_record_ids.csv'
    final_df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    
    print(f"\nSonuçlar '{output_filename}' dosyasına kaydedildi.")
    print("İşte ilk 5 sonuç:")
    display(final_df.head())

Hata: Veri seti '/data/final_filtered_data.csv' konumunda bulunamadı. Lütfen dosya yolunu kontrol edin.
'OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora' klasöründe dosya araması başlatılıyor...

Belirtilen dosya adlarından hiçbiri bulunamadı.

In [1]:
import pandas as pd
import os

# --- Adım 1: Dosya Yollarını ve Veri Setini Tanımlama ---
# Veri setinizin dosya yolu
# Bu yolun projenizin ana dizinine göreceli olduğunu varsayıyoruz.
dataframe_file_path = os.path.join('data', 'final_filtered_data.csv')

# Arama yapılacak ana klasörün yolu
search_directory = "OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora"

# Arama dışında tutulacak klasörün adı
excluded_folder_name = 'gitReview'

print("İşlem başlatılıyor...")
print(f"Veri seti yolu: '{dataframe_file_path}'")
print(f"Arama yapılacak ana dizin: '{search_directory}'")
print(f"Arama dışında tutulacak klasör: '{excluded_folder_name}'")

# --- Adım 2: Veri Setini Yükle ve Filtrele ---
try:
    df = pd.read_csv(dataframe_file_path)
    valid_filenames = df[df['Filename'].notna() & (df['Filename'] != '-') & (df['Filename'] != '')]['Filename'].unique()
    print(f"\nToplam {len(valid_filenames)} adet dosya adı aranacak.\n")

except FileNotFoundError:
    print(f"Hata: Veri seti '{dataframe_file_path}' konumunda bulunamadı. Lütfen dosya yolunu kontrol edin.")
    exit()
except KeyError:
    print("Hata: 'Filename' sütunu bulunamadı. Lütfen sütun adını kontrol edin.")
    exit()

# --- Adım 3: Belirtilen Klasörde Dosya Arama ---
found_files = []

# Dosya yolu mevcut değilse uyarı ver
if not os.path.exists(search_directory):
    print(f"Hata: Arama yapılacak dizin '{search_directory}' bulunamadı. Lütfen dizin yolunu kontrol edin.")
    exit()

print(f"'{search_directory}' klasöründe dosya araması başlatılıyor...")

for root, dirs, files in os.walk(search_directory):
    # Arama dışında tutulacak klasörü kontrol et
    # Bu kontrol, alt klasörlere inmeden önce yapılır
    if excluded_folder_name in root.split(os.sep):
        print(f"  '{root}' dizini arama dışında tutuluyor.")
        continue # Bu dizini atla ve bir sonraki dizine geç

    for file in files:
        if file in valid_filenames:
            full_path = os.path.join(root, file)
            found_files.append({'filename': file, 'full_path': full_path})
            print(f"  Bulundu: {full_path}")

# --- Adım 4: Bulunan Dosyaları DataFrame'e Dönüştürme ve Eşleştirme ---
if not found_files:
    print("\nBelirtilen dosya adlarından hiçbiri bulunamadı.")
else:
    found_df = pd.DataFrame(found_files)
    merged_df = pd.merge(df, found_df, on='Filename', how='inner')
    final_df = merged_df[['record_id', 'Filename', 'full_path']]

    print(f"\n✅ Toplam {len(final_df)} adet kayıt başarıyla eşleştirildi.")

    # --- Adım 5: Sonuçları CSV Olarak Kaydetme ---
    output_filename = 'matched_files_with_record_ids.csv'
    final_df.to_csv(output_filename, index=False, encoding='utf-8-sig')

    print(f"\nSonuçlar '{output_filename}' dosyasına kaydedildi.")
    print("İşte ilk 5 sonuç:")
    display(final_df.head())

İşlem başlatılıyor...
Veri seti yolu: 'data/final_filtered_data.csv'
Arama yapılacak ana dizin: 'OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora'
Arama dışında tutulacak klasör: 'gitReview'

Toplam 143 adet dosya adı aranacak.

Hata: Arama yapılacak dizin 'OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora' bulunamadı. Lütfen dizin yolunu kontrol edin.
'OneDrive - ASKERİ FABRİKA VE TERSANE İŞLETME A.Ş (ASFAT)/kisiselAlan/AKU_Doktora' klasöründe dosya araması başlatılıyor...

Belirtilen dosya adlarından hiçbiri bulunamadı.